export interface GenderForm {
  word: string;
  pronunciation?: string;
}

export interface VocabItem {
  portuguese: string;
  english: string;
  pronunciation?: string;
  example?: string;
  /** Paired masculine/feminine forms (e.g. Um / Uma, Dois / Duas) */
  genderForms?: { masculine: GenderForm; feminine: GenderForm };
  /** Single-form gender marker (e.g. obrigado = masculine, obrigada = feminine) */
  gender?: "masculine" | "feminine";
}

export interface Lesson {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  bgColor: string;
  level: 1 | 2;
  items: VocabItem[];
}

// ─── Level 1 ──────────────────────────────────────────────────────────────────

const level1: Lesson[] = [
  {
    id: "begin-here",
    level: 1,
    title: "Begin Here",
    description: "Essential phrases to get you started in Portugal",
    icon: "🇵🇹",
    color: "#046A38",
    bgColor: "#f0fdf4",
    items: [
      {
        portuguese: "Olá",
        english: "Hello",
        pronunciation: "oh-LAH",
        example: "Olá! Bom dia.",
      },
      {
        portuguese: "Tchau",
        english: "Goodbye",
        pronunciation: "chow",
        example: "Tchau! Até logo.",
      },
      {
        portuguese: "Bom dia",
        english: "Good morning",
        pronunciation: "bohm DEE-ah",
        example: "Bom dia! Como está?",
      },
      {
        portuguese: "Boa tarde",
        english: "Good afternoon",
        pronunciation: "BOH-ah TAR-deh",
        example: "Boa tarde, senhor.",
      },
      {
        portuguese: "Boa noite",
        english: "Good night",
        pronunciation: "BOH-ah NOY-teh",
        example: "Boa noite, durma bem.",
      },
      {
        portuguese: "Por favor",
        english: "Please",
        pronunciation: "por fah-VOR",
        example: "Um café, por favor.",
      },
      {
        portuguese: "Obrigado",
        english: "Thank you (male speaker)",
        pronunciation: "oh-bree-GAH-doo",
        example: "Obrigado pela ajuda.",
        gender: "masculine",
      },
      {
        portuguese: "Obrigada",
        english: "Thank you (female speaker)",
        pronunciation: "oh-bree-GAH-dah",
        example: "Obrigada pela ajuda.",
        gender: "feminine",
      },
      {
        portuguese: "Desculpe",
        english: "Sorry / Excuse me",
        pronunciation: "desh-KOOL-peh",
        example: "Desculpe, não entendi.",
      },
      {
        portuguese: "Onde fica…?",
        english: "Where is…?",
        pronunciation: "ON-deh FEE-kah",
        example: "Onde fica o metro?",
      },
      {
        portuguese: "Quanto custa?",
        english: "How much does it cost?",
        pronunciation: "KWAN-too KOOSH-tah",
        example: "Quanto custa este bilhete?",
      },
      {
        portuguese: "Fala inglês?",
        english: "Do you speak English?",
        pronunciation: "FAH-lah ing-GLESH",
        example: "Desculpe, fala inglês?",
      },
      {
        portuguese: "Não percebo.",
        english: "I don't understand.",
        pronunciation: "nowng pehr-SEH-boo",
        example: "Desculpe, não percebo.",
      },
      {
        portuguese: "Preciso de ajuda.",
        english: "I need help.",
        pronunciation: "preh-SEE-zoo deh ah-ZHOO-dah",
        example: "Com licença, preciso de ajuda.",
      },
    ],
  },
  {
    id: "greeting-someone",
    level: 1,
    title: "Greeting Someone",
    description: "How to introduce yourself and meet people in Portugal",
    icon: "😊",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    items: [
      {
        portuguese: "Muito prazer.",
        english: "Nice to meet you.",
        pronunciation: "MWEE-too prah-ZEHR",
        example: "Olá! Chamo-me Ana. Muito prazer.",
      },
      {
        portuguese: "Como se chama?",
        english: "What is your name? (formal)",
        pronunciation: "KOH-moo seh SHA-mah",
        example: "Bom dia! Como se chama?",
      },
      {
        portuguese: "Como te chamas?",
        english: "What is your name? (informal)",
        pronunciation: "KOH-moo teh SHA-mash",
        example: "Olá! Como te chamas?",
      },
      {
        portuguese: "Chamo-me…",
        english: "My name is…",
        pronunciation: "SHA-moo meh",
        example: "Chamo-me João.",
      },
      {
        portuguese: "Sou de…",
        english: "I am from…",
        pronunciation: "soh deh",
        example: "Sou de Inglaterra.",
      },
      {
        portuguese: "Bem-vindo.",
        english: "Welcome. (to a male)",
        pronunciation: "beng-VEEN-doo",
        example: "Bem-vindo a Portugal!",
        gender: "masculine",
      },
      {
        portuguese: "Bem-vinda.",
        english: "Welcome. (to a female)",
        pronunciation: "beng-VEEN-dah",
        example: "Bem-vinda a Portugal!",
        gender: "feminine",
      },
    ],
  },
  {
    id: "greetings-time-of-day",
    level: 1,
    title: "Greetings by Time of Day",
    description: "How to say hello depending on the time of day in European Portuguese",
    icon: "🕐",
    color: "#D97706",
    bgColor: "#FEF3C7",
    items: [
      {
        portuguese: "Bom dia!",
        english: "Good morning!",
        pronunciation: "bong JEE-ah",
        example: "Bom dia! Como estás?",
        notes: "Manhã (Morning) — used until around midday",
      },
      {
        portuguese: "Boa tarde!",
        english: "Good afternoon!",
        pronunciation: "BOH-ah TAR-deh",
        example: "Boa tarde! Tudo bem?",
        notes: "Tarde (Afternoon) — used from midday until dusk",
      },
      {
        portuguese: "Boa noite!",
        english: "Good evening!",
        pronunciation: "BOH-ah NOY-teh",
        example: "Boa noite! Até amanhã.",
        notes: "Noite (Evening/Night) — used after dark; also used to say goodnight",
      },
    ],
  },
  {
    id: "greetings-quiz",
    level: 1,
    title: "Greetings — Multiple Choice",
    description: "Test yourself on common Portuguese greetings: formal, informal, and time of day",
    icon: "🧠",
    color: "#0F766E",
    bgColor: "#F0FDFA",
    items: [
      {
        portuguese: "Olá!",
        english: "Hello!",
        pronunciation: "oh-LAH",
        example: "Olá! Como estás?",
        notes: "Both formal & informal · Used in Portugal and Brazil",
      },
      {
        portuguese: "Bom dia!",
        english: "Good morning!",
        pronunciation: "bong JEE-ah",
        example: "Bom dia! Tudo bem?",
        notes: "Both formal & informal · Used until noon · Portugal and Brazil",
      },
      {
        portuguese: "Boa tarde!",
        english: "Good afternoon!",
        pronunciation: "BOH-ah TAR-deh",
        example: "Boa tarde! Em que posso ajudar?",
        notes: "Both formal & informal · Used after noon until evening · Portugal and Brazil",
      },
      {
        portuguese: "Boa noite!",
        english: "Good evening!",
        pronunciation: "BOH-ah NOY-teh",
        example: "Boa noite! Até amanhã.",
        notes: "Both formal & informal · Used in the evening · Portugal and Brazil",
      },
      {
        portuguese: "Oi!",
        english: "Hi!",
        pronunciation: "oy",
        example: "Oi! Estás bem?",
        notes: "Informal · More common in Brazil — rarely used in Portugal",
      },
      {
        portuguese: "Tudo bem?",
        english: "Is everything okay?",
        pronunciation: "TOO-doo beng",
        example: "Olá! Tudo bem?",
        notes: "Informal · Common way to ask 'how are you?' · Portugal and Brazil",
      },
      {
        portuguese: "Como está?",
        english: "How are you? (formal)",
        pronunciation: "KOH-moo esh-TAH",
        example: "Bom dia! Como está?",
        notes: "Formal · Uses você/senhor/senhora form · More common in Portugal",
      },
      {
        portuguese: "Como vai?",
        english: "How are you going?",
        pronunciation: "KOH-moo vye",
        example: "Como vai? Tudo bem?",
        notes: "Formal · Shows interest in well-being · Portugal and Brazil",
      },
    ],
  },
  {
    id: "how-are-you",
    level: 1,
    title: "How Are You?",
    description: "Ways to ask and answer 'how are you?' in European Portuguese",
    icon: "🤝",
    color: "#7c3aed",
    bgColor: "#f5f3ff",
    items: [
      {
        portuguese: "Como está?",
        english: "How are you? (formal)",
        pronunciation: "KOH-moo esh-TAH",
        example: "Bom dia! Como está?",
      },
      {
        portuguese: "Como estás?",
        english: "How are you? (informal)",
        pronunciation: "KOH-moo esh-TASH",
        example: "Olá! Como estás?",
      },
      {
        portuguese: "Tudo bem?",
        english: "Is everything okay?",
        pronunciation: "TOO-doo beng",
        example: "Olá! Tudo bem?",
      },
      {
        portuguese: "Como vai?",
        english: "How are you doing?",
        pronunciation: "KOH-moo vye",
        example: "Boa tarde! Como vai?",
      },
      {
        portuguese: "Estou bem.",
        english: "I'm fine.",
        pronunciation: "esh-TOH beng",
        example: "Estou bem, obrigado.",
      },
      {
        portuguese: "Mais ou menos.",
        english: "So-so.",
        pronunciation: "mysh oh MEH-noosh",
        example: "Mais ou menos, e tu?",
      },
    ],
  },
  {
    id: "greetings",
    level: 1,
    title: "Greetings",
    description: "How to greet people in Portuguese",
    icon: "👋",
    color: "#2563eb",
    bgColor: "#dbeafe",
    items: [
      { portuguese: "Olá", english: "Hello", pronunciation: "oh-LAH", example: "Olá, como está?" },
      { portuguese: "Bom dia", english: "Good morning", pronunciation: "bohm DEE-ah", example: "Bom dia! Que belo tempo hoje." },
      { portuguese: "Boa tarde", english: "Good afternoon", pronunciation: "bo-ah TAR-deh", example: "Boa tarde, senhor." },
      { portuguese: "Boa noite", english: "Good evening", pronunciation: "bo-ah NOY-teh", example: "Boa noite, durma bem." },
      { portuguese: "Tchau", english: "Bye", pronunciation: "chow", example: "Tchau! Até amanhã." },
      { portuguese: "Até logo", english: "See you soon", pronunciation: "ah-TEH LOH-goo", example: "Até logo! Cuida-te." },
      {
        portuguese: "Boa sorte!",
        english: "Good luck!",
        pronunciation: "BOH-ah SOR-teh",
        example: "Boa sorte no exame!",
        notes: "Said when wishing someone well before a test, interview, or challenge",
      },
    ],
  },
  {
    id: "real-conversation-1",
    level: 1,
    title: "Real Conversation 1",
    description: "A real-world greeting exchange between two friends",
    icon: "🗣️",
    color: "#d97706",
    bgColor: "#fef3c7",
    items: [
      {
        portuguese: "Olá, Diogo! Tudo bem?",
        english: "Hello, Diogo! Is everything okay?",
        pronunciation: "oh-LAH dee-OH-goo TOO-doo beng",
        example: "Margarida sees Diogo: Olá, Diogo! Tudo bem?",
      },
      {
        portuguese: "Olá, Margarida! Sim, como estás?",
        english: "Hello, Margarida! Yes, how are you?",
        pronunciation: "oh-LAH mar-gah-REE-dah sing KOH-moo esh-TASH",
        example: "Diogo replies: Olá, Margarida! Sim, como estás?",
      },
    ],
  },
  {
    id: "first-conversation",
    level: 1,
    title: "First Conversation",
    description: "A real back-and-forth dialogue using everyday greetings",
    icon: "💬",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    items: [
      {
        portuguese: "Olá! Bom dia.",
        english: "Hello! Good morning.",
        pronunciation: "oh-LAH bohm DEE-ah",
        example: "A says to B: Olá! Bom dia.",
      },
      {
        portuguese: "Bom dia! Como estás?",
        english: "Good morning! How are you?",
        pronunciation: "bohm DEE-ah KOH-moo esh-TASH",
        example: "B replies: Bom dia! Como estás?",
      },
      {
        portuguese: "Estou bem, obrigado! Até logo.",
        english: "I'm great, thanks! See you soon.",
        pronunciation: "esh-TOH beng oh-bree-GAH-doo ah-TEH LOH-goo",
        example: "A replies: Estou bem, obrigado! Até logo.",
      },
      {
        portuguese: "Tchau!",
        english: "Bye!",
        pronunciation: "chow",
        example: "B waves and says: Tchau!",
      },
    ],
  },
  {
    id: "travel-phrases",
    level: 1,
    title: "Travel Phrases",
    description: "Essential phrases for getting around in Portugal",
    icon: "✈️",
    color: "#0891b2",
    bgColor: "#e0f2fe",
    items: [
      {
        portuguese: "Onde fica…?",
        english: "Where is …?",
        pronunciation: "ON-deh FEE-kah",
        example: "Onde fica a estação de metro?",
      },
      {
        portuguese: "Como chegar a…?",
        english: "How do I get to …?",
        pronunciation: "KOH-moo cheh-GAHR ah",
        example: "Como chegar a Lisboa?",
      },
      {
        portuguese: "Eu estou perdido.",
        english: "I am lost. (male speaker)",
        pronunciation: "eh-ooh eh-STOW pehr-DEE-doo",
        example: "Com licença, eu estou perdido.",
        gender: "masculine",
      },
      {
        portuguese: "Eu estou perdida.",
        english: "I am lost. (female speaker)",
        pronunciation: "eh-ooh eh-STOW pehr-DEE-dah",
        example: "Com licença, eu estou perdida.",
        gender: "feminine",
      },
      {
        portuguese: "Continue",
        english: "Continue",
        pronunciation: "kohn-TEEN-yoo-eh",
        example: "Continue em frente.",
      },
      {
        portuguese: "Esquerda",
        english: "Left",
        pronunciation: "ehs-KEHR-dah",
        example: "Vire à esquerda.",
      },
      {
        portuguese: "Direita",
        english: "Right",
        pronunciation: "dee-RAY-tah",
        example: "Vire à direita.",
      },
      {
        portuguese: "A primeira rua",
        english: "The first road",
        pronunciation: "ah preem-AY-rah ROO-ah",
        example: "Vire à esquerda na primeira rua.",
      },
      {
        portuguese: "A segunda rua",
        english: "The second road",
        pronunciation: "ah seh-GOON-dah ROO-ah",
        example: "Vire à direita na segunda rua.",
      },
      {
        portuguese: "A terceira rua",
        english: "The third road",
        pronunciation: "ah tehr-SAY-rah ROO-ah",
        example: "Siga até à terceira rua.",
      },
      {
        portuguese: "Vire à esquerda",
        english: "Turn left",
        pronunciation: "VEER-eh ah ehs-KEHR-dah",
        example: "Vire à esquerda no semáforo.",
      },
      {
        portuguese: "Vire à direita",
        english: "Turn right",
        pronunciation: "VEER-eh ah dee-RAY-tah",
        example: "Vire à direita na próxima rua.",
      },
      {
        portuguese: "Siga em frente",
        english: "Go straight ahead",
        pronunciation: "SEE-gah ehn FREHN-chee",
        example: "Siga em frente por 200 metros.",
      },
      {
        portuguese: "Atrás",
        english: "Behind",
        pronunciation: "ah-TRAHS",
        example: "O hotel está atrás da estação.",
      },
      {
        portuguese: "Ao lado de",
        english: "Next to",
        pronunciation: "ow LAH-doo deh",
        example: "O café está ao lado de um museu.",
      },
      {
        portuguese: "Entre",
        english: "Between",
        pronunciation: "EHN-tchee",
        example: "A farmácia está entre o banco e o correio.",
      },
      {
        portuguese: "Norte",
        english: "North",
        pronunciation: "NOR-teh",
        example: "Siga em direção ao norte.",
      },
      {
        portuguese: "Sul",
        english: "South",
        pronunciation: "sool",
        example: "Lisboa fica no sul do país.",
      },
      {
        portuguese: "Este",
        english: "East",
        pronunciation: "ES-teh",
        example: "O sol nasce a este.",
      },
      {
        portuguese: "Oeste",
        english: "West",
        pronunciation: "o-ES-teh",
        example: "Portugal fica a oeste da Europa.",
      },
      {
        portuguese: "A estação",
        english: "The station",
        pronunciation: "ah ehs-tah-SOWNG",
        example: "Onde fica a estação de comboio?",
      },
      {
        portuguese: "O autocarro",
        english: "The bus",
        pronunciation: "oh ow-toh-KAH-rroo",
        example: "Que autocarro vai ao centro?",
      },
      {
        portuguese: "O táxi",
        english: "The taxi",
        pronunciation: "oh TAHK-see",
        example: "Pode chamar um táxi?",
      },
      {
        portuguese: "O metro",
        english: "The subway / underground",
        pronunciation: "oh MEH-troo",
        example: "Onde fica a estação de metro?",
      },
      {
        portuguese: "A paragem de autocarro",
        english: "The bus stop",
        pronunciation: "ah pah-RAH-zheng deh ow-toh-KAH-rroo",
        example: "A paragem de autocarro fica ali.",
      },
      {
        portuguese: "O ponto de táxi",
        english: "The taxi stand",
        pronunciation: "oh PON-too deh TAHK-see",
        example: "Há um ponto de táxi aqui perto?",
      },
      {
        portuguese: "A bicicleta",
        english: "The bicycle",
        pronunciation: "ah bee-see-KLEH-tah",
        example: "Posso alugar uma bicicleta?",
      },
      {
        portuguese: "O passeio",
        english: "The pavement / sidewalk",
        pronunciation: "oh pah-SAY-oo",
        example: "Caminhe pelo passeio.",
      },
      {
        portuguese: "A pé",
        english: "On foot",
        pronunciation: "ah peh",
        example: "Posso ir a pé daqui?",
      },
      {
        portuguese: "A rua",
        english: "The street",
        pronunciation: "ah RROO-ah",
        example: "Vire à direita na próxima rua.",
      },
      {
        portuguese: "A avenida",
        english: "The avenue",
        pronunciation: "ah ah-veh-NEE-dah",
        example: "Siga pela avenida em frente.",
      },
      {
        portuguese: "O semáforo",
        english: "The traffic light",
        pronunciation: "oh seh-MAH-foh-roo",
        example: "Vire à esquerda no semáforo.",
      },
      {
        portuguese: "O cruzamento",
        english: "The crossroads / intersection",
        pronunciation: "oh kroo-zah-MEN-too",
        example: "Pare no cruzamento.",
      },
      {
        portuguese: "O estacionamento",
        english: "The car park",
        pronunciation: "oh ehs-tah-see-oh-NAH-men-too",
        example: "Há um estacionamento aqui perto?",
      },
      {
        portuguese: "O mapa",
        english: "The map",
        pronunciation: "oh MAH-pah",
        example: "Tem um mapa da cidade?",
      },
      {
        portuguese: "A esquina",
        english: "The corner",
        pronunciation: "ah ehs-KEE-nah",
        example: "O café fica na esquina.",
      },
    ],
  },
  {
    id: "numbers",
    level: 1,
    title: "Numbers",
    description: "Count from zero to one hundred in Portuguese",
    icon: "🔢",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    items: [
      { portuguese: "Zero", english: "0", pronunciation: "ZEH-roo" },
      {
        portuguese: "Um / Uma", english: "1", pronunciation: "oong / OO-mah",
        genderForms: {
          masculine: { word: "Um", pronunciation: "oong" },
          feminine: { word: "Uma", pronunciation: "OO-mah" },
        },
      },
      {
        portuguese: "Dois / Duas", english: "2", pronunciation: "doysh / DOO-ash",
        genderForms: {
          masculine: { word: "Dois", pronunciation: "doysh" },
          feminine: { word: "Duas", pronunciation: "DOO-ash" },
        },
      },
      { portuguese: "Três", english: "3", pronunciation: "tresh" },
      { portuguese: "Quatro", english: "4", pronunciation: "KWAH-troo" },
      { portuguese: "Cinco", english: "5", pronunciation: "SING-koo" },
      { portuguese: "Seis", english: "6", pronunciation: "saysh" },
      { portuguese: "Sete", english: "7", pronunciation: "SEH-teh" },
      { portuguese: "Oito", english: "8", pronunciation: "OY-too" },
      { portuguese: "Nove", english: "9", pronunciation: "NOH-veh" },
      { portuguese: "Dez", english: "10", pronunciation: "desh" },
      { portuguese: "Onze", english: "11", pronunciation: "ON-zeh" },
      { portuguese: "Doze", english: "12", pronunciation: "DOH-zeh" },
      { portuguese: "Vinte", english: "20", pronunciation: "VEEN-teh" },
      { portuguese: "Trinta", english: "30", pronunciation: "TREEN-tah" },
      { portuguese: "Quarenta", english: "40", pronunciation: "kwah-REN-tah" },
      { portuguese: "Cinquenta", english: "50", pronunciation: "sing-KWEN-tah" },
      { portuguese: "Cem", english: "100", pronunciation: "seng" },
    ],
  },
  {
    id: "food",
    level: 1,
    title: "Food & Drink",
    description: "Order food and drinks like a local in Portugal",
    icon: "🍽️",
    color: "#d97706",
    bgColor: "#fef3c7",
    items: [
      { portuguese: "Água", english: "Water", pronunciation: "AH-gwah", example: "Uma água, por favor." },
      { portuguese: "Vinho", english: "Wine", pronunciation: "VEE-nyoo", example: "Um copo de vinho tinto." },
      { portuguese: "Café", english: "Coffee", pronunciation: "kah-FEH", example: "Um café, por favor." },
      { portuguese: "Pão", english: "Bread", pronunciation: "powng", example: "O pão é delicioso." },
      { portuguese: "Peixe", english: "Fish", pronunciation: "PAY-sheh", example: "O peixe está fresco." },
      { portuguese: "Carne", english: "Meat", pronunciation: "KAR-neh", example: "Quero carne assada." },
      { portuguese: "Frango", english: "Chicken", pronunciation: "FRAN-goo", example: "Um prato de frango." },
      { portuguese: "Bacalhau", english: "Codfish", pronunciation: "bah-kah-LYOW", example: "O bacalhau é o prato nacional." },
      { portuguese: "Sobremesa", english: "Dessert", pronunciation: "soh-breh-MEH-zah", example: "Que sobremesas têm?" },
      { portuguese: "Pastel de nata", english: "Custard tart", pronunciation: "pash-TEL deh NAH-tah", example: "Dois pastéis de nata, por favor." },
      { portuguese: "Queijo", english: "Cheese", pronunciation: "KAY-zhoo", example: "Um prato de queijo." },
      { portuguese: "Cerveja", english: "Beer", pronunciation: "ser-VAY-zhah", example: "Uma cerveja bem fresca." },
      { portuguese: "A conta", english: "The bill", pronunciation: "ah KON-tah", example: "Pode trazer a conta?" },
      { portuguese: "Está delicioso", english: "It's delicious", pronunciation: "esh-TAH deh-lee-SYOH-zoo", example: "Está delicioso, obrigado!" },
    ],
  },
  {
    id: "groceries",
    level: 1,
    title: "Groceries",
    description: "Everyday food and drink vocabulary for the supermarket",
    icon: "🛒",
    color: "#16a34a",
    bgColor: "#f0fdf4",
    items: [
      { portuguese: "Pão", english: "Bread", pronunciation: "powng", example: "Quero um pão, por favor." },
      { portuguese: "Leite", english: "Milk", pronunciation: "LAY-teh", example: "Um litro de leite, por favor." },
      { portuguese: "Queijo", english: "Cheese", pronunciation: "KAY-zhoo", example: "Tem queijo da serra?" },
      { portuguese: "Ovos", english: "Eggs", pronunciation: "OH-voosh", example: "Uma dúzia de ovos." },
      { portuguese: "Carne", english: "Meat", pronunciation: "KAR-neh", example: "Onde fica a secção de carne?" },
      { portuguese: "Frango", english: "Chicken", pronunciation: "FRAN-goo", example: "Um frango assado, por favor." },
      { portuguese: "Peixe", english: "Fish", pronunciation: "PAY-sheh", example: "O peixe está fresco hoje?" },
      { portuguese: "Legumes", english: "Vegetables", pronunciation: "leh-GOO-mesh", example: "Quero legumes frescos." },
      { portuguese: "Frutas", english: "Fruit", pronunciation: "FROO-tash", example: "Que frutas têm hoje?" },
      { portuguese: "Arroz", english: "Rice", pronunciation: "ah-RROSH", example: "Um pacote de arroz." },
      { portuguese: "Feijão", english: "Beans", pronunciation: "fay-ZHOWNG", example: "Uma lata de feijão." },
      { portuguese: "Açúcar", english: "Sugar", pronunciation: "ah-SOO-kahr", example: "Um quilo de açúcar." },
      { portuguese: "Sal", english: "Salt", pronunciation: "sahl", example: "Preciso de sal." },
      { portuguese: "Óleo", english: "Oil", pronunciation: "OH-lyoo", example: "Um frasco de óleo." },
      { portuguese: "Café", english: "Coffee", pronunciation: "kah-FEH", example: "Um pacote de café." },
      { portuguese: "Água", english: "Water", pronunciation: "AH-gwah", example: "Água com gás ou sem gás?" },
      { portuguese: "Cerveja", english: "Beer", pronunciation: "sehr-VAY-zhah", example: "Uma cerveja bem fresca." },
      { portuguese: "Vinho", english: "Wine", pronunciation: "VEEN-yoo", example: "Um vinho tinto, por favor." },
      { portuguese: "Manteiga", english: "Butter", pronunciation: "mahn-TAY-gah", example: "Pão com manteiga." },
      { portuguese: "Massa", english: "Pasta", pronunciation: "MAH-sah", example: "Um pacote de massa." },
    ],
  },
  {
    id: "shopping",
    level: 1,
    title: "Shopping & Restaurant",
    description: "Essential phrases for shops and eating out in Portugal",
    icon: "🛍️",
    color: "#e11d48",
    bgColor: "#fff1f2",
    items: [
      {
        portuguese: "Quanto custa?",
        english: "How much does it cost?",
        pronunciation: "KWAN-too KOOSH-tah",
        example: "Quanto custa este casaco?",
      },
      {
        portuguese: "Quero isto.",
        english: "I want this.",
        pronunciation: "KAY-roo EESH-too",
        example: "Quero isto, por favor.",
      },
      {
        portuguese: "O menu, por favor.",
        english: "The menu, please.",
        pronunciation: "oh MEH-noo, por fah-VOR",
        example: "Boa tarde! O menu, por favor.",
      },
      {
        portuguese: "A conta, por favor.",
        english: "The bill, please.",
        pronunciation: "ah KON-tah, por fah-VOR",
        example: "Com licença, a conta, por favor.",
      },
      {
        portuguese: "Entrada",
        english: "Appetiser",
        pronunciation: "ehn-TRAH-dah",
        example: "O que tem de entrada?",
      },
      {
        portuguese: "Prato principal",
        english: "Main course",
        pronunciation: "PRAH-too preen-see-PAHL",
        example: "Qual é o prato principal do dia?",
      },
      {
        portuguese: "Sobremesa",
        english: "Dessert",
        pronunciation: "soh-breh-MEH-zah",
        example: "Que sobremesas têm?",
      },
      {
        portuguese: "Bebida",
        english: "Beverage / Drink",
        pronunciation: "beh-BEE-dah",
        example: "Que bebidas têm?",
      },
      {
        portuguese: "Vegetais",
        english: "Vegetables",
        pronunciation: "veh-zheh-TAYSH",
        example: "Quero um prato de vegetais.",
      },
      {
        portuguese: "Sopa",
        english: "Soup",
        pronunciation: "SOH-pah",
        example: "Uma sopa do dia, por favor.",
      },
      {
        portuguese: "Salada",
        english: "Salad",
        pronunciation: "sah-LAH-dah",
        example: "Uma salada mista, por favor.",
      },
      {
        portuguese: "Sumo",
        english: "Juice",
        pronunciation: "SOO-moo",
        example: "Um sumo de laranja, por favor.",
      },
      {
        portuguese: "Batata frita",
        english: "French fries / Chips",
        pronunciation: "bah-TAH-tah FREE-tah",
        example: "Com batata frita, por favor.",
      },
    ],
  },
  {
    id: "travel",
    level: 1,
    title: "Travel",
    description: "Navigate Portugal with confidence",
    icon: "✈️",
    color: "#059669",
    bgColor: "#d1fae5",
    items: [
      { portuguese: "Onde fica...?", english: "Where is...?", pronunciation: "ON-deh FEE-kah", example: "Onde fica o aeroporto?" },
      { portuguese: "Como chego a...?", english: "How do I get to...?", pronunciation: "KOH-moo SHEH-goo ah", example: "Como chego ao centro?" },
      { portuguese: "Metro", english: "Underground / Metro", pronunciation: "MEH-troo", example: "Onde fica o metro?" },
      { portuguese: "Autocarro", english: "Bus", pronunciation: "ow-toh-KAH-rroo", example: "Que autocarro vai ao centro?" },
      { portuguese: "Comboio", english: "Train", pronunciation: "kom-BOY-oo", example: "O comboio parte às 9h." },
      { portuguese: "Táxi", english: "Taxi", pronunciation: "TAX-ee", example: "Pode chamar um táxi?" },
      { portuguese: "Aeroporto", english: "Airport", pronunciation: "ah-eh-rop-OR-too", example: "Vou ao aeroporto." },
      { portuguese: "Hotel", english: "Hotel", pronunciation: "oh-TEL", example: "Tenho reserva no hotel." },
      { portuguese: "Quarto", english: "Room", pronunciation: "KWAR-too", example: "O meu quarto é o 204." },
      { portuguese: "Bilhete", english: "Ticket", pronunciation: "bee-LYEH-teh", example: "Dois bilhetes, por favor." },
      { portuguese: "Museu", english: "Museum", pronunciation: "moo-ZEH-oo", example: "O museu fecha às 18h." },
      { portuguese: "Praia", english: "Beach", pronunciation: "PRI-ah", example: "Vamos à praia?" },
      { portuguese: "Farmácia", english: "Pharmacy", pronunciation: "far-MAH-syah", example: "Há uma farmácia perto?" },
      { portuguese: "Hospital", english: "Hospital", pronunciation: "osh-pee-TAL", example: "Preciso ir ao hospital." },
    ],
  },
  {
    id: "definite-articles",
    level: 1,
    title: "Definite Articles",
    description: "The words for 'the' — gender and number in European Portuguese",
    icon: "📖",
    color: "#7c3aed",
    bgColor: "#f5f3ff",
    items: [
      {
        portuguese: "O",
        english: "The (masculine singular)",
        pronunciation: "oo",
        example: "O homem é simpático — The man is friendly.",
        genderForms: { masculine: { word: "O", pronunciation: "oo" }, feminine: { word: "A", pronunciation: "ah" } },
      },
      {
        portuguese: "A",
        english: "The (feminine singular)",
        pronunciation: "ah",
        example: "A mulher é simpática — The woman is friendly.",
      },
      {
        portuguese: "Os",
        english: "The (masculine plural)",
        pronunciation: "oosh",
        example: "Os rapazes jogam futebol — The boys play football.",
        genderForms: { masculine: { word: "Os", pronunciation: "oosh" }, feminine: { word: "As", pronunciation: "ash" } },
      },
      {
        portuguese: "As",
        english: "The (feminine plural)",
        pronunciation: "ash",
        example: "As raparigas estão na escola — The girls are at school.",
      },
      {
        portuguese: "O / A",
        english: "The — singular (masc. / fem.)",
        pronunciation: "oo / ah",
        example: "O livro e a caneta — The book and the pen.",
        genderForms: { masculine: { word: "O", pronunciation: "oo" }, feminine: { word: "A", pronunciation: "ah" } },
      },
      {
        portuguese: "Os / As",
        english: "The — plural (masc. / fem.)",
        pronunciation: "oosh / ash",
        example: "Os livros e as canetas — The books and the pens.",
        genderForms: { masculine: { word: "Os", pronunciation: "oosh" }, feminine: { word: "As", pronunciation: "ash" } },
      },
    ],
  },
];

// ─── Level 2 ──────────────────────────────────────────────────────────────────

const level2: Lesson[] = [
  {
    id: "pronouns-prepositions",
    level: 2,
    title: "Tonic Pronouns",
    description: "Master pronouns used with Por, Para & Até",
    icon: "🔤",
    color: "#e11d48",
    bgColor: "#fff1f2",
    items: [
      // ── Subject pronoun ──
      { portuguese: "Eu", english: "I", pronunciation: "eh-oo", example: "Eu posso escutar podcasts — I can listen to podcasts." },
      // ── Contractions: de + article ──
      { portuguese: "do", english: "of the / from the (de + o)", pronunciation: "doo", example: "Gostas do verão? — Do you like summer?" },
      { portuguese: "da", english: "of the / from the (de + a)", pronunciation: "dah", example: "Gostas da primavera? — Do you like spring?" },
      // ── The three key prepositions (tap to hear) ──
      {
        portuguese: "Ao",
        english: "At / To the (a + o)",
        pronunciation: "ow",
        example: "Vou ao mercado ao fim de semana — I go to the market at the weekend.",
      },
      {
        portuguese: "Por",
        english: "For / By / Through",
        pronunciation: "por",
        example: "Este presente é por mim — This gift is from me.",
      },
      {
        portuguese: "Para",
        english: "For / To / In order to",
        pronunciation: "PAH-rah",
        example: "Isto é para ti — This is for you.",
      },
      {
        portuguese: "Até",
        english: "Until / Up to / As far as",
        pronunciation: "ah-TEH",
        example: "Esperei até elas — I waited for them.",
      },
      // ── Tonic pronouns (used after prepositions) ──
      { portuguese: "Mim", english: "Me (after preposition)", pronunciation: "ming", example: "Ele comprou isto para mim — He bought this for me." },
      { portuguese: "Ti", english: "You — singular, informal (after preposition)", pronunciation: "tee", example: "Faço isto por ti — I do this for you." },
      { portuguese: "Ele", english: "Him (after preposition)", pronunciation: "EH-leh", example: "Falei com ele — I spoke with him." },
      { portuguese: "Ela", english: "Her (after preposition)", pronunciation: "EH-lah", example: "O livro é para ela — The book is for her." },
      { portuguese: "Nós", english: "Us (after preposition)", pronunciation: "nosh", example: "Eles trabalham para nós — They work for us." },
      { portuguese: "Vós", english: "You — plural, formal (after preposition)", pronunciation: "vosh", example: "O rei falou para vós — The king spoke to you." },
      { portuguese: "Eles", english: "Them — masculine (after preposition)", pronunciation: "EH-lesh", example: "Comprei flores para eles — I bought flowers for them." },
      { portuguese: "Elas", english: "Them — feminine (after preposition)", pronunciation: "EH-lash", example: "O professor falou com elas — The teacher spoke with them." },
      // ── Common phrases with prepositions + tonic pronouns ──
      { portuguese: "Por mim", english: "For me / As far as I'm concerned", pronunciation: "por ming", example: "Por mim, pode ficar — As far as I'm concerned, you can stay." },
      { portuguese: "Para ti", english: "For you", pronunciation: "PAH-rah tee", example: "Trouxe algo para ti — I brought something for you." },
      { portuguese: "Até ela", english: "Until her / Up to her", pronunciation: "ah-TEH EH-lah", example: "Esperamos até ela chegar — We waited until she arrived." },
      { portuguese: "Sem mim", english: "Without me", pronunciation: "seng ming", example: "Foram sem mim — They left without me." },
      { portuguese: "Com ele", english: "With him", pronunciation: "kong EH-leh", example: "Vim com ele — I came with him." },
    ],
  },
  {
    id: "essential-verbs",
    level: 2,
    title: "Essential Verbs",
    description: "The most important Portuguese verbs in everyday use",
    icon: "⚡",
    color: "#4f46e5",
    bgColor: "#eef2ff",
    items: [
      { portuguese: "Ser", english: "To be (permanent)", pronunciation: "sehr", example: "Eu sou português — I am Portuguese." },
      { portuguese: "Estar", english: "To be (temporary state)", pronunciation: "esh-TAR", example: "Estou cansado — I am tired." },
      { portuguese: "Ter", english: "To have", pronunciation: "tehr", example: "Tenho fome — I am hungry (lit. I have hunger)." },
      { portuguese: "Fazer", english: "To do / To make", pronunciation: "fah-ZEHR", example: "O que queres fazer? — What do you want to do?" },
      { portuguese: "Ir", english: "To go", pronunciation: "eer", example: "Vou ao mercado — I am going to the market." },
      { portuguese: "Vir", english: "To come", pronunciation: "veer", example: "Venho já — I'm coming right now." },
      { portuguese: "Poder", english: "To be able to / Can", pronunciation: "poh-DEHR", example: "Posso ajudar? — Can I help?" },
      { portuguese: "Posso", english: "I can", pronunciation: "POH-soo", example: "Posso escutar podcasts e cozinhar ao mesmo tempo — I can listen to podcasts and cook at the same time." },
      { portuguese: "Querer", english: "To want", pronunciation: "keh-REHR", example: "Quero aprender português — I want to learn Portuguese." },
      { portuguese: "Saber", english: "To know (facts / how to)", pronunciation: "sah-BEHR", example: "Sei falar um pouco — I know how to speak a little." },
      { portuguese: "Falar", english: "To speak", pronunciation: "fah-LAR", example: "Falo português todos os dias — I speak Portuguese every day." },
      { portuguese: "Ouvir", english: "To hear / To listen", pronunciation: "oh-VEER", example: "Ouço música portuguesa — I listen to Portuguese music." },
      { portuguese: "Escutar", english: "To listen", pronunciation: "esh-koo-TAR", example: "Gosto de escutar podcasts — I like to listen to podcasts." },
      { portuguese: "Ver", english: "To see / To watch", pronunciation: "vehr", example: "Vejo televisão à noite — I watch TV at night." },
      { portuguese: "Gostar", english: "To like", pronunciation: "goosh-TAR", example: "Gosto muito de Portugal — I really like Portugal." },
      { portuguese: "Gostas", english: "You like", pronunciation: "GOSH-tash", example: "Gostas do verão e da primavera, certo? — You like summer and spring, right?" },
      { portuguese: "Precisar", english: "To need", pronunciation: "preh-see-ZAR", example: "Preciso de ajuda — I need help." },
      { portuguese: "Trabalhar", english: "To work", pronunciation: "trah-bah-LYAR", example: "Trabalho em Lisboa — I work in Lisbon." },
      { portuguese: "Cozinhar", english: "To cook", pronunciation: "koh-zee-NYAR", example: "Gosto de cozinhar ao fim de semana — I like to cook at the weekend." },
    ],
  },
  {
    id: "everyday-nouns",
    level: 2,
    title: "Everyday Nouns",
    description: "Key nouns for home, family, work and daily life",
    icon: "🏠",
    color: "#0d9488",
    bgColor: "#f0fdfa",
    items: [
      { portuguese: "Casa", english: "House / Home", pronunciation: "KAH-zah", example: "A minha casa é pequena — My house is small." },
      { portuguese: "Família", english: "Family", pronunciation: "fah-MEE-lyah", example: "A minha família é grande — My family is large." },
      {
        portuguese: "Amigo / Amiga", english: "Friend", pronunciation: "ah-MEE-goo / ah-MEE-gah",
        genderForms: { masculine: { word: "Amigo", pronunciation: "ah-MEE-goo" }, feminine: { word: "Amiga", pronunciation: "ah-MEE-gah" } },
      },
      { portuguese: "Trabalho", english: "Work / Job", pronunciation: "trah-BAH-lyoo", example: "O meu trabalho é difícil — My work is difficult." },
      { portuguese: "Tempo", english: "Time / Weather", pronunciation: "TEM-poo", example: "Não tenho tempo — I don't have time." },
      { portuguese: "Dinheiro", english: "Money", pronunciation: "dee-NYAY-roo", example: "Não tenho dinheiro suficiente — I don't have enough money." },
      { portuguese: "Cidade", english: "City", pronunciation: "see-DAH-deh", example: "Lisboa é uma cidade bonita — Lisbon is a beautiful city." },
      { portuguese: "País", english: "Country", pronunciation: "pah-EESH", example: "Portugal é um país lindo — Portugal is a beautiful country." },
      { portuguese: "Língua", english: "Language / Tongue", pronunciation: "LING-gwah", example: "A língua portuguesa é rica — The Portuguese language is rich." },
      { portuguese: "Carro", english: "Car", pronunciation: "KAH-rroo", example: "O meu carro é novo — My car is new." },
      { portuguese: "Escola", english: "School", pronunciation: "esh-KOH-lah", example: "Os filhos estão na escola — The children are at school." },
      { portuguese: "Livro", english: "Book", pronunciation: "LEE-vroo", example: "Estou a ler um livro — I am reading a book." },
      { portuguese: "Podcast", english: "Podcast", pronunciation: "POD-kast", example: "Gosto de ouvir podcasts em português — I like listening to podcasts in Portuguese." },
      { portuguese: "Palavra", english: "Word", pronunciation: "pah-LAH-vrah", example: "Aprendo uma palavra nova por dia — I learn one new word a day." },
      { portuguese: "Nome", english: "Name", pronunciation: "NOH-meh", example: "Qual é o teu nome? — What is your name?" },
      { portuguese: "Vida", english: "Life", pronunciation: "VEE-dah", example: "A vida em Portugal é boa — Life in Portugal is good." },
      { portuguese: "Verão", english: "Summer", pronunciation: "veh-ROWNG", example: "Gostas do verão? — Do you like summer?" },
      { portuguese: "Primavera", english: "Spring", pronunciation: "pree-mah-VEH-rah", example: "A primavera em Portugal é linda — Spring in Portugal is beautiful." },
    ],
  },
  {
    id: "adjectives",
    level: 2,
    title: "Adjectives",
    description: "Describe people, places and things in Portuguese",
    icon: "🌟",
    color: "#ea580c",
    bgColor: "#fff7ed",
    items: [
      {
        portuguese: "Bom / Boa", english: "Good",
        pronunciation: "bong / BOH-ah",
        genderForms: { masculine: { word: "Bom", pronunciation: "bong" }, feminine: { word: "Boa", pronunciation: "BOH-ah" } },
        example: "Um bom amigo — A good friend.",
      },
      {
        portuguese: "Boa sorte!",
        english: "Good luck!",
        pronunciation: "BOH-ah SOR-teh",
        example: "Boa sorte no exame! — Good luck in the exam!",
        notes: "Uses boa (feminine of bom) because sorte (luck) is a feminine noun. A common, natural expression.",
      },
      {
        portuguese: "Mau / Má", english: "Bad",
        pronunciation: "mow / mah",
        genderForms: { masculine: { word: "Mau", pronunciation: "mow" }, feminine: { word: "Má", pronunciation: "mah" } },
        example: "Um dia mau — A bad day.",
      },
      {
        portuguese: "Grande", english: "Big / Great",
        pronunciation: "GRAN-deh",
        example: "Uma cidade grande — A big city.",
      },
      {
        portuguese: "Pequeno / Pequena", english: "Small / Little",
        pronunciation: "peh-KAY-noo / peh-KAY-nah",
        genderForms: { masculine: { word: "Pequeno", pronunciation: "peh-KAY-noo" }, feminine: { word: "Pequena", pronunciation: "peh-KAY-nah" } },
        example: "Uma casa pequena — A small house.",
      },
      {
        portuguese: "Bonito / Bonita", english: "Beautiful / Pretty",
        pronunciation: "boo-NEE-too / boo-NEE-tah",
        genderForms: { masculine: { word: "Bonito", pronunciation: "boo-NEE-too" }, feminine: { word: "Bonita", pronunciation: "boo-NEE-tah" } },
        example: "Que dia bonito! — What a beautiful day!",
      },
      {
        portuguese: "Novo / Nova", english: "New / Young",
        pronunciation: "NOH-voo / NOH-vah",
        genderForms: { masculine: { word: "Novo", pronunciation: "NOH-voo" }, feminine: { word: "Nova", pronunciation: "NOH-vah" } },
        example: "Um livro novo — A new book.",
      },
      {
        portuguese: "Velho / Velha", english: "Old",
        pronunciation: "VEH-lyoo / VEH-lyah",
        genderForms: { masculine: { word: "Velho", pronunciation: "VEH-lyoo" }, feminine: { word: "Velha", pronunciation: "VEH-lyah" } },
        example: "Um amigo velho — An old friend.",
      },
      { portuguese: "Quente", english: "Hot / Warm", pronunciation: "KEN-teh", example: "O café está quente — The coffee is hot." },
      {
        portuguese: "Frio / Fria", english: "Cold",
        pronunciation: "FREE-oo / FREE-ah",
        genderForms: { masculine: { word: "Frio", pronunciation: "FREE-oo" }, feminine: { word: "Fria", pronunciation: "FREE-ah" } },
        example: "A água está fria — The water is cold.",
      },
      { portuguese: "Feliz", english: "Happy", pronunciation: "feh-LEESH", example: "Estou muito feliz — I am very happy." },
      { portuguese: "Triste", english: "Sad", pronunciation: "TREESH-teh", example: "Ela parece triste — She seems sad." },
      {
        portuguese: "Cansado / Cansada", english: "Tired",
        pronunciation: "kan-SAH-doo / kan-SAH-dah",
        genderForms: { masculine: { word: "Cansado", pronunciation: "kan-SAH-doo" }, feminine: { word: "Cansada", pronunciation: "kan-SAH-dah" } },
        example: "Estou muito cansado hoje — I am very tired today.",
      },
      { portuguese: "Fácil", english: "Easy", pronunciation: "FAH-seel", example: "O português é fácil! — Portuguese is easy!" },
      { portuguese: "Difícil", english: "Difficult", pronunciation: "dee-FEE-seel", example: "A gramática é difícil — Grammar is difficult." },
      { portuguese: "Interessante", english: "Interesting", pronunciation: "in-teh-reh-SAN-teh", example: "Que história interessante! — What an interesting story!" },
      {
        portuguese: "Mesmo / Mesma", english: "Same",
        pronunciation: "MEZ-moo / MEZ-mah",
        genderForms: { masculine: { word: "Mesmo", pronunciation: "MEZ-moo" }, feminine: { word: "Mesma", pronunciation: "MEZ-mah" } },
        example: "Somos da mesma cidade — We are from the same city.",
      },
      { portuguese: "Certo", english: "Right / Correct", pronunciation: "SEHR-too", example: "Gostas do verão e da primavera, certo? — You like summer and spring, right?" },
    ],
  },
  {
    id: "intermediate-numbers",
    level: 2,
    title: "Advanced Numbers",
    description: "Ordinals, large numbers and useful expressions",
    icon: "🔢",
    color: "#7c3aed",
    bgColor: "#f5f3ff",
    items: [
      { portuguese: "Primeiro / Primeira", english: "First", pronunciation: "pree-MAY-roo / pree-MAY-rah",
        genderForms: { masculine: { word: "Primeiro", pronunciation: "pree-MAY-roo" }, feminine: { word: "Primeira", pronunciation: "pree-MAY-rah" } },
        example: "O primeiro andar — The first floor." },
      { portuguese: "Segundo / Segunda", english: "Second", pronunciation: "seh-GOON-doo / seh-GOON-dah",
        genderForms: { masculine: { word: "Segundo", pronunciation: "seh-GOON-doo" }, feminine: { word: "Segunda", pronunciation: "seh-GOON-dah" } } },
      { portuguese: "Terceiro / Terceira", english: "Third", pronunciation: "tehr-SAY-roo / tehr-SAY-rah",
        genderForms: { masculine: { word: "Terceiro", pronunciation: "tehr-SAY-roo" }, feminine: { word: "Terceira", pronunciation: "tehr-SAY-rah" } } },
      { portuguese: "Quarto / Quarta", english: "Fourth", pronunciation: "KWAR-too / KWAR-tah",
        genderForms: { masculine: { word: "Quarto", pronunciation: "KWAR-too" }, feminine: { word: "Quarta", pronunciation: "KWAR-tah" } } },
      { portuguese: "Quinto / Quinta", english: "Fifth", pronunciation: "KEEN-too / KEEN-tah",
        genderForms: { masculine: { word: "Quinto", pronunciation: "KEEN-too" }, feminine: { word: "Quinta", pronunciation: "KEEN-tah" } } },
      { portuguese: "Décimo / Décima", english: "Tenth", pronunciation: "DEH-see-moo / DEH-see-mah",
        genderForms: { masculine: { word: "Décimo", pronunciation: "DEH-see-moo" }, feminine: { word: "Décima", pronunciation: "DEH-see-mah" } } },
      { portuguese: "Cem", english: "100 (exact)", pronunciation: "seng", example: "Cem euros — One hundred euros." },
      { portuguese: "Cento e um", english: "101", pronunciation: "SEN-too ee oong", example: "Cento e um anos — One hundred and one years." },
      { portuguese: "Duzentos", english: "200", pronunciation: "doo-ZEN-toosh", example: "Duzentos quilómetros — Two hundred kilometres." },
      { portuguese: "Quinhentos", english: "500", pronunciation: "kee-NYEN-toosh", example: "Quinhentas pessoas — Five hundred people." },
      { portuguese: "Mil", english: "1,000", pronunciation: "meel", example: "Mil e uma noites — One Thousand and One Nights." },
      { portuguese: "Um milhão", english: "1,000,000", pronunciation: "oong mee-LYOWNG", example: "Um milhão de euros — One million euros." },
      { portuguese: "Metade", english: "Half", pronunciation: "meh-TAH-deh", example: "Metade do preço — Half the price." },
      { portuguese: "Um terço", english: "One third", pronunciation: "oong TEHR-soo", example: "Um terço da população — One third of the population." },
      { portuguese: "Ambos / Ambas", english: "Both", pronunciation: "AM-boosh / AM-bash",
        genderForms: { masculine: { word: "Ambos", pronunciation: "AM-boosh" }, feminine: { word: "Ambas", pronunciation: "AM-bash" } },
        example: "Ambos os filhos — Both children." },
    ],
  },
  {
    id: "possessive-pronouns",
    level: 2,
    title: "Possessive Pronouns",
    description: "Express ownership — my, your, his, her, our, their",
    icon: "🔑",
    color: "#0891b2",
    bgColor: "#ecfeff",
    items: [
      { portuguese: "Meu / Minha", english: "My (masc. / fem.)", pronunciation: "MAY-oo / MEE-nyah",
        genderForms: { masculine: { word: "Meu", pronunciation: "MAY-oo" }, feminine: { word: "Minha", pronunciation: "MEE-nyah" } },
        example: "O meu livro é novo — My book is new." },
      { portuguese: "Meus / Minhas", english: "My — plural (masc. / fem.)", pronunciation: "MAY-oosh / MEE-nyash",
        genderForms: { masculine: { word: "Meus", pronunciation: "MAY-oosh" }, feminine: { word: "Minhas", pronunciation: "MEE-nyash" } },
        example: "Os meus livros são novos — My books are new." },
      { portuguese: "Teu / Tua", english: "Your — sing. (masc. / fem.)", pronunciation: "TAY-oo / TOO-ah",
        genderForms: { masculine: { word: "Teu", pronunciation: "TAY-oo" }, feminine: { word: "Tua", pronunciation: "TOO-ah" } },
        example: "A tua casa é bonita — Your house is beautiful." },
      { portuguese: "Teus / Tuas", english: "Your — plural (masc. / fem.)", pronunciation: "TAY-oosh / TOO-ash",
        genderForms: { masculine: { word: "Teus", pronunciation: "TAY-oosh" }, feminine: { word: "Tuas", pronunciation: "TOO-ash" } } },
      { portuguese: "Seu / Sua", english: "His / Her / Your (masc. / fem.)", pronunciation: "SAY-oo / SOO-ah",
        genderForms: { masculine: { word: "Seu", pronunciation: "SAY-oo" }, feminine: { word: "Sua", pronunciation: "SOO-ah" } },
        example: "Os seus vestidos são lindos — Her dresses are beautiful." },
      { portuguese: "Seus / Suas", english: "His / Her / Your — plural (masc. / fem.)", pronunciation: "SAY-oosh / SOO-ash",
        genderForms: { masculine: { word: "Seus", pronunciation: "SAY-oosh" }, feminine: { word: "Suas", pronunciation: "SOO-ash" } } },
      { portuguese: "Nosso / Nossa", english: "Our (masc. / fem.)", pronunciation: "NOH-soo / NOH-sah",
        genderForms: { masculine: { word: "Nosso", pronunciation: "NOH-soo" }, feminine: { word: "Nossa", pronunciation: "NOH-sah" } },
        example: "A nossa casa é grande — Our house is big." },
      { portuguese: "Nossos / Nossas", english: "Our — plural (masc. / fem.)", pronunciation: "NOH-soosh / NOH-sash",
        genderForms: { masculine: { word: "Nossos", pronunciation: "NOH-soosh" }, feminine: { word: "Nossas", pronunciation: "NOH-sash" } } },
      { portuguese: "Vosso / Vossa", english: "Your — plural formal (masc. / fem.)", pronunciation: "VOH-soo / VOH-sah",
        genderForms: { masculine: { word: "Vosso", pronunciation: "VOH-soo" }, feminine: { word: "Vossa", pronunciation: "VOH-sah" } },
        example: "A vossa apresentação foi um sucesso! — Your presentation was a success!" },
      { portuguese: "Dele", english: "His (contraction: de + ele)", pronunciation: "DEH-leh",
        example: "O carro dele é novo — His car is new." },
      { portuguese: "Dela", english: "Her (contraction: de + ela)", pronunciation: "DEH-lah",
        example: "Os vestidos dela são lindos — Her dresses are beautiful." },
      { portuguese: "Deles", english: "Their — masc. (contraction: de + eles)", pronunciation: "DEH-lesh",
        example: "A casa deles é grande — Their house is big." },
      { portuguese: "Delas", english: "Their — fem. (contraction: de + elas)", pronunciation: "DEH-lash",
        example: "O trabalho delas é incrível — Their work is amazing." },
    ],
  },
  {
    id: "conjunctions",
    level: 2,
    title: "Conjunctions",
    description: "Connect ideas with linking words and conjunctive phrases",
    icon: "🔗",
    color: "#7c3aed",
    bgColor: "#f5f3ff",
    items: [
      // ── Simple conjunctions ────────────────────────────────────────────────
      { portuguese: "e", english: "and", pronunciation: "ee",
        example: "Gosto de café e de chá — I like coffee and tea." },
      { portuguese: "ou", english: "or", pronunciation: "oh",
        example: "Queres sair ou ficar em casa? — Do you want to go out or stay home?" },
      { portuguese: "mas", english: "but", pronunciation: "mash",
        example: "Quero ir, mas estou cansado — I want to go but I'm tired." },
      { portuguese: "porque", english: "because", pronunciation: "por-KEH",
        example: "Fico em casa porque está a chover — I stay home because it's raining." },
      { portuguese: "então", english: "so / then", pronunciation: "en-TOWNG",
        example: "Estava com fome, então comi — I was hungry, so I ate." },
      // ── Correlative pairs ─────────────────────────────────────────────────
      { portuguese: "não só… mas também", english: "not only… but also", pronunciation: "nowng SOH … mash tahm-BAYNG",
        example: "Não só falo português, mas também falo inglês — Not only do I speak Portuguese, but I also speak English." },
      { portuguese: "ou… ou", english: "either… or", pronunciation: "oh … oh",
        example: "Ou comes agora ou ficas com fome — Either you eat now or you go hungry." },
      { portuguese: "nem… nem", english: "neither… nor", pronunciation: "neng … neng",
        example: "Não tenho nem fome nem sede — I'm neither hungry nor thirsty." },
      { portuguese: "quer… quer", english: "whether… or", pronunciation: "kehr … kehr",
        example: "Quer chova, quer faça sol, vou sair — Whether it rains or shines, I'll go out." },
      // ── Conjunctive phrases ───────────────────────────────────────────────
      { portuguese: "mesmo que", english: "even if / although", pronunciation: "MEZ-moo keh",
        example: "Mesmo que chova, vou sair — Even if it rains, I will go out." },
      { portuguese: "desde que", english: "as long as / since", pronunciation: "DEZ-deh keh",
        example: "Posso ir desde que chegue a tempo — I can go as long as I arrive on time." },
      { portuguese: "a não ser que", english: "unless", pronunciation: "ah nowng sehr keh",
        example: "Vou, a não ser que esteja doente — I'll go unless I'm sick." },
      { portuguese: "já que", english: "since / given that", pronunciation: "zhah keh",
        example: "Já que estás aqui, ajuda-me — Since you're here, help me." },
      { portuguese: "senão", english: "otherwise / but", pronunciation: "seh-NOWNG",
        example: "Apressa-te, senão perdes o autocarro — Hurry up, otherwise you'll miss the bus." },
      { portuguese: "uma vez que", english: "once / since", pronunciation: "OO-mah vez keh",
        example: "Uma vez que entendas, fica fácil — Once you understand, it becomes easy." },
    ],
  },
];

// ─── Combined export ───────────────────────────────────────────────────────────

export const lessons: Lesson[] = [...level1, ...level2];
export const lessons1 = level1;
export const lessons2 = level2;
