// Generated by scripts/generate-portuguese-audio.mjs.
export const portugueseAudioManifest: Record<string, { feminine: string; masculine: string }> = {
  "Olá": {
    "feminine": "/audio/pt-pt/feminine-dd859ed3db1eeee5.mp3",
    "masculine": "/audio/pt-pt/masculine-0eab6d61aa776bf3.mp3"
  },
  "Bom dia": {
    "feminine": "/audio/pt-pt/feminine-691abb8e9e66fb15.mp3",
    "masculine": "/audio/pt-pt/masculine-39030c13323d20ea.mp3"
  },
  "Boa tarde": {
    "feminine": "/audio/pt-pt/feminine-913b2770f7de1233.mp3",
    "masculine": "/audio/pt-pt/masculine-b70cc818a7d90e58.mp3"
  },
  "Boa noite": {
    "feminine": "/audio/pt-pt/feminine-47a6a13e54781828.mp3",
    "masculine": "/audio/pt-pt/masculine-a4a6a31296169a0a.mp3"
  },
  "Como está?": {
    "feminine": "/audio/pt-pt/feminine-69ef767b69be2251.mp3",
    "masculine": "/audio/pt-pt/masculine-0012011405f5a492.mp3"
  },
  "Obrigado": {
    "feminine": "/audio/pt-pt/feminine-691211c9d18f4be8.mp3",
    "masculine": "/audio/pt-pt/masculine-7bf2e73fbad0c274.mp3"
  },
  "Obrigada": {
    "feminine": "/audio/pt-pt/feminine-8a71d14a067c7973.mp3",
    "masculine": "/audio/pt-pt/masculine-40a6acb28ab567d3.mp3"
  },
  "Por favor": {
    "feminine": "/audio/pt-pt/feminine-1e5126970ff5aba1.mp3",
    "masculine": "/audio/pt-pt/masculine-37790479073132b7.mp3"
  },
  "De nada": {
    "feminine": "/audio/pt-pt/feminine-b3031f26e26080fa.mp3",
    "masculine": "/audio/pt-pt/masculine-44baa3c9ad5cfd86.mp3"
  },
  "Adeus": {
    "feminine": "/audio/pt-pt/feminine-4447079a81c881a3.mp3",
    "masculine": "/audio/pt-pt/masculine-4c2c7d04c92b2de2.mp3"
  },
  "um": {
    "feminine": "/audio/pt-pt/feminine-6404004c67928594.mp3",
    "masculine": "/audio/pt-pt/masculine-53a0c9add1be8293.mp3"
  },
  "dois": {
    "feminine": "/audio/pt-pt/feminine-cb7d7af2b29f7208.mp3",
    "masculine": "/audio/pt-pt/masculine-70825fad33e9155f.mp3"
  },
  "três": {
    "feminine": "/audio/pt-pt/feminine-ab8b4fa54890e222.mp3",
    "masculine": "/audio/pt-pt/masculine-9b26bc99b7d2fef9.mp3"
  },
  "quatro": {
    "feminine": "/audio/pt-pt/feminine-98c33a3a969b2913.mp3",
    "masculine": "/audio/pt-pt/masculine-f54d05a3f6e31112.mp3"
  },
  "cinco": {
    "feminine": "/audio/pt-pt/feminine-1d3f8342ea659a60.mp3",
    "masculine": "/audio/pt-pt/masculine-1e45b8d8c61774a5.mp3"
  },
  "seis": {
    "feminine": "/audio/pt-pt/feminine-c2ced8353e18b3ae.mp3",
    "masculine": "/audio/pt-pt/masculine-76051e455e442d06.mp3"
  },
  "sete": {
    "feminine": "/audio/pt-pt/feminine-57f12d8062b1bc0a.mp3",
    "masculine": "/audio/pt-pt/masculine-6bc7572803b0b38e.mp3"
  },
  "oito": {
    "feminine": "/audio/pt-pt/feminine-5e19c778bb8c694c.mp3",
    "masculine": "/audio/pt-pt/masculine-484c0b6776d79b67.mp3"
  },
  "nove": {
    "feminine": "/audio/pt-pt/feminine-7fedeb52a3b047d2.mp3",
    "masculine": "/audio/pt-pt/masculine-426cbdc926132c72.mp3"
  },
  "dez": {
    "feminine": "/audio/pt-pt/feminine-34065e69f8778514.mp3",
    "masculine": "/audio/pt-pt/masculine-2c4436019fca5adf.mp3"
  },
  "Queria leite e pão, por favor.": {
    "feminine": "/audio/pt-pt/feminine-adec8c4c6bb64044.mp3",
    "masculine": "/audio/pt-pt/masculine-9e4432c1e5ade47b.mp3"
  },
  "água": {
    "feminine": "/audio/pt-pt/feminine-7d77f4d67d00610b.mp3",
    "masculine": "/audio/pt-pt/masculine-31fe6ac8dde18380.mp3"
  },
  "pão": {
    "feminine": "/audio/pt-pt/feminine-207aaa5b9e871987.mp3",
    "masculine": "/audio/pt-pt/masculine-187428d218933261.mp3"
  },
  "Queijo": {
    "feminine": "/audio/pt-pt/feminine-032be38fc3570a20.mp3",
    "masculine": "/audio/pt-pt/masculine-f2bcaf4bc18a7d5f.mp3"
  },
  "A conta, por favor": {
    "feminine": "/audio/pt-pt/feminine-66fd57ab1b4cb83c.mp3",
    "masculine": "/audio/pt-pt/masculine-b483027519ba7343.mp3"
  },
  "sopa": {
    "feminine": "/audio/pt-pt/feminine-7b3c1c67c9e2f876.mp3",
    "masculine": "/audio/pt-pt/masculine-c7fdf5405ca92665.mp3"
  },
  "leite": {
    "feminine": "/audio/pt-pt/feminine-526e1531ae02c098.mp3",
    "masculine": "/audio/pt-pt/masculine-93e2829ff1a39e3e.mp3"
  },
  "sumo de laranja": {
    "feminine": "/audio/pt-pt/feminine-bad815ee9be35c5c.mp3",
    "masculine": "/audio/pt-pt/masculine-a2ef3eb1707e32ad.mp3"
  },
  "um pastel de nata": {
    "feminine": "/audio/pt-pt/feminine-1c5af3f7cab49f2c.mp3",
    "masculine": "/audio/pt-pt/masculine-98a811f3e1e9f9d4.mp3"
  },
  "sem açúcar": {
    "feminine": "/audio/pt-pt/feminine-1e5ec56caa044af0.mp3",
    "masculine": "/audio/pt-pt/masculine-b1b41a89d3f33a8a.mp3"
  },
  "Onde fica a estação?": {
    "feminine": "/audio/pt-pt/feminine-2a756b172265f1df.mp3",
    "masculine": "/audio/pt-pt/masculine-2932656c987781df.mp3"
  },
  "Bilhete": {
    "feminine": "/audio/pt-pt/feminine-a8004f437cd0a65f.mp3",
    "masculine": "/audio/pt-pt/masculine-d1e6fa7b1c43137f.mp3"
  },
  "À esquerda": {
    "feminine": "/audio/pt-pt/feminine-73ebabc82573db46.mp3",
    "masculine": "/audio/pt-pt/masculine-60c60c5aba1ac858.mp3"
  },
  "À direita": {
    "feminine": "/audio/pt-pt/feminine-f4e15768db2353a9.mp3",
    "masculine": "/audio/pt-pt/masculine-95f187b6e6b290ca.mp3"
  },
  "Tenho uma reserva": {
    "feminine": "/audio/pt-pt/feminine-b6ba9413aae14a25.mp3",
    "masculine": "/audio/pt-pt/masculine-c36f2d7e2180f910.mp3"
  },
  "Onde fica a paragem?": {
    "feminine": "/audio/pt-pt/feminine-ad46aa24e51abd0d.mp3",
    "masculine": "/audio/pt-pt/masculine-e601c1adc8c05a77.mp3"
  },
  "O metro": {
    "feminine": "/audio/pt-pt/feminine-71c96ffb629dc9a5.mp3",
    "masculine": "/audio/pt-pt/masculine-389ee27e44b0266e.mp3"
  },
  "Em frente": {
    "feminine": "/audio/pt-pt/feminine-ed624ab9b5bb9c42.mp3",
    "masculine": "/audio/pt-pt/masculine-f8dd96e86b553e56.mp3"
  },
  "Quanto custa o bilhete?": {
    "feminine": "/audio/pt-pt/feminine-66feed5f3fdb10d5.mp3",
    "masculine": "/audio/pt-pt/masculine-73e4f96c719dea44.mp3"
  },
  "Preciso de um táxi": {
    "feminine": "/audio/pt-pt/feminine-474c9fab1c2126a7.mp3",
    "masculine": "/audio/pt-pt/masculine-4b135fe124616a18.mp3"
  },
  "Chamo-me Ana": {
    "feminine": "/audio/pt-pt/feminine-e462383f10625edd.mp3",
    "masculine": "/audio/pt-pt/masculine-d28c80f636626723.mp3"
  },
  "Como se chama?": {
    "feminine": "/audio/pt-pt/feminine-63c28362a8a27e3f.mp3",
    "masculine": "/audio/pt-pt/masculine-83004ae726bee454.mp3"
  },
  "Sou de Inglaterra": {
    "feminine": "/audio/pt-pt/feminine-92acae9fe05408ba.mp3",
    "masculine": "/audio/pt-pt/masculine-c53c8e59c6ebbe04.mp3"
  },
  "Muito prazer": {
    "feminine": "/audio/pt-pt/feminine-cff0a3641d0c4996.mp3",
    "masculine": "/audio/pt-pt/masculine-1fca03e1a1771b2c.mp3"
  },
  "E você?": {
    "feminine": "/audio/pt-pt/feminine-b256aa7f13850987.mp3",
    "masculine": "/audio/pt-pt/masculine-a4275262bd9c75e2.mp3"
  },
  "Muito obrigado": {
    "feminine": "/audio/pt-pt/feminine-8b914431889aba35.mp3",
    "masculine": "/audio/pt-pt/masculine-f05a80fea3d9f908.mp3"
  },
  "Com licença": {
    "feminine": "/audio/pt-pt/feminine-639edbd2cec99e53.mp3",
    "masculine": "/audio/pt-pt/masculine-a6371a24edb3395f.mp3"
  },
  "Peço desculpa": {
    "feminine": "/audio/pt-pt/feminine-e8b9dd2879563185.mp3",
    "masculine": "/audio/pt-pt/masculine-0afb81bf40455843.mp3"
  },
  "Não faz mal": {
    "feminine": "/audio/pt-pt/feminine-49128e26f237d460.mp3",
    "masculine": "/audio/pt-pt/masculine-4285898b7f6ff8e3.mp3"
  },
  "Que horas são?": {
    "feminine": "/audio/pt-pt/feminine-745cca5b9be85314.mp3",
    "masculine": "/audio/pt-pt/masculine-cf1dc6deac990b1d.mp3"
  },
  "É uma hora": {
    "feminine": "/audio/pt-pt/feminine-681edbbcd1cb1c5f.mp3",
    "masculine": "/audio/pt-pt/masculine-b7781fd025ab8ff6.mp3"
  },
  "São duas horas": {
    "feminine": "/audio/pt-pt/feminine-7bdde40dbd657dc2.mp3",
    "masculine": "/audio/pt-pt/masculine-604550cfcfbc5de4.mp3"
  },
  "Hoje é segunda-feira": {
    "feminine": "/audio/pt-pt/feminine-899435d27d83be60.mp3",
    "masculine": "/audio/pt-pt/masculine-f31b6ee10d79e258.mp3"
  },
  "Amanhã de manhã": {
    "feminine": "/audio/pt-pt/feminine-3674f2f60b36815c.mp3",
    "masculine": "/audio/pt-pt/masculine-6f038f005735a872.mp3"
  },
  "Esta é a minha mãe": {
    "feminine": "/audio/pt-pt/feminine-92d1f1e61be83dda.mp3",
    "masculine": "/audio/pt-pt/masculine-bb9ad618f705de32.mp3"
  },
  "Este é o meu pai": {
    "feminine": "/audio/pt-pt/feminine-b6580a286005b337.mp3",
    "masculine": "/audio/pt-pt/masculine-be78733e4cd300a6.mp3"
  },
  "Tenho uma irmã": {
    "feminine": "/audio/pt-pt/feminine-6f58dd538333b9c3.mp3",
    "masculine": "/audio/pt-pt/masculine-5d543a8296b7b05c.mp3"
  },
  "Tenho um irmão": {
    "feminine": "/audio/pt-pt/feminine-5bf12f6d0696f60b.mp3",
    "masculine": "/audio/pt-pt/masculine-cbb959fc35087bfa.mp3"
  },
  "A minha família": {
    "feminine": "/audio/pt-pt/feminine-3cd440650d889097.mp3",
    "masculine": "/audio/pt-pt/masculine-0365e21067ea1dab.mp3"
  },
  "Esta é a cozinha": {
    "feminine": "/audio/pt-pt/feminine-e2a7d97588cd3005.mp3",
    "masculine": "/audio/pt-pt/masculine-d073b1115676a75a.mp3"
  },
  "O quarto é pequeno": {
    "feminine": "/audio/pt-pt/feminine-d4448fa25d83b95a.mp3",
    "masculine": "/audio/pt-pt/masculine-9daa5f49bb26a68b.mp3"
  },
  "A casa de banho": {
    "feminine": "/audio/pt-pt/feminine-2353a8c60a797794.mp3",
    "masculine": "/audio/pt-pt/masculine-66dc7ed36c5bff88.mp3"
  },
  "Onde está a chave?": {
    "feminine": "/audio/pt-pt/feminine-68c815d0ddda8f53.mp3",
    "masculine": "/audio/pt-pt/masculine-db40b4e00f785463.mp3"
  },
  "A chave está na mesa": {
    "feminine": "/audio/pt-pt/feminine-43c7d8cec8759d5c.mp3",
    "masculine": "/audio/pt-pt/masculine-265f1fed25a656b1.mp3"
  },
  "Acordo às sete": {
    "feminine": "/audio/pt-pt/feminine-8a70c9e45c269c72.mp3",
    "masculine": "/audio/pt-pt/masculine-7006e5e99e61562f.mp3"
  },
  "Tomo o pequeno-almoço": {
    "feminine": "/audio/pt-pt/feminine-f4cb9e5f48ddf5a6.mp3",
    "masculine": "/audio/pt-pt/masculine-be5886ba7350d485.mp3"
  },
  "Vou para o trabalho": {
    "feminine": "/audio/pt-pt/feminine-3e1ad07dd7aaa720.mp3",
    "masculine": "/audio/pt-pt/masculine-80275b3714cecfdb.mp3"
  },
  "Janto às oito": {
    "feminine": "/audio/pt-pt/feminine-57480d5502daffde.mp3",
    "masculine": "/audio/pt-pt/masculine-ed57d1eac669a995.mp3"
  },
  "Deito-me cedo": {
    "feminine": "/audio/pt-pt/feminine-c12bfb3ceb95468e.mp3",
    "masculine": "/audio/pt-pt/masculine-b2d9a171c83d2efd.mp3"
  },
  "Quanto custa isto?": {
    "feminine": "/audio/pt-pt/feminine-c26c75a3f19289af.mp3",
    "masculine": "/audio/pt-pt/masculine-67412b13d0be95e3.mp3"
  },
  "Tem um tamanho maior?": {
    "feminine": "/audio/pt-pt/feminine-b2108b8b76460ddd.mp3",
    "masculine": "/audio/pt-pt/masculine-9bbfa1f17e33e224.mp3"
  },
  "Quero o azul": {
    "feminine": "/audio/pt-pt/feminine-5d3a3af6d4c8fbf9.mp3",
    "masculine": "/audio/pt-pt/masculine-b0773b2504d9f426.mp3"
  },
  "Posso experimentar?": {
    "feminine": "/audio/pt-pt/feminine-9d58ca6621c06c1d.mp3",
    "masculine": "/audio/pt-pt/masculine-9a324d1dc0affda2.mp3"
  },
  "Pago com cartão": {
    "feminine": "/audio/pt-pt/feminine-b00f02306648d26b.mp3",
    "masculine": "/audio/pt-pt/masculine-f23ada7794073508.mp3"
  },
  "Onde fica o centro?": {
    "feminine": "/audio/pt-pt/feminine-d572d6dbef6a0d8f.mp3",
    "masculine": "/audio/pt-pt/masculine-aa4faf0e12e53cd2.mp3"
  },
  "Siga em frente": {
    "feminine": "/audio/pt-pt/feminine-39d99754638df5d0.mp3",
    "masculine": "/audio/pt-pt/masculine-9f0e1031ffc59dd8.mp3"
  },
  "Vire à esquerda": {
    "feminine": "/audio/pt-pt/feminine-b7ee437b9fc540d8.mp3",
    "masculine": "/audio/pt-pt/masculine-00bc5c477e24fa28.mp3"
  },
  "Vire à direita": {
    "feminine": "/audio/pt-pt/feminine-54aada9e465f9f45.mp3",
    "masculine": "/audio/pt-pt/masculine-38608c6bb7fa6e68.mp3"
  },
  "É perto daqui": {
    "feminine": "/audio/pt-pt/feminine-2822f7ac6a71b263.mp3",
    "masculine": "/audio/pt-pt/masculine-b16a352031bb091f.mp3"
  },
  "Um bilhete para Lisboa": {
    "feminine": "/audio/pt-pt/feminine-5151494ba6e46348.mp3",
    "masculine": "/audio/pt-pt/masculine-3c7502050d2a0f29.mp3"
  },
  "A que horas parte?": {
    "feminine": "/audio/pt-pt/feminine-40cd405f68ca2a05.mp3",
    "masculine": "/audio/pt-pt/masculine-5f0cd0db34038d03.mp3"
  },
  "É este o comboio?": {
    "feminine": "/audio/pt-pt/feminine-b71edc6f37d523dc.mp3",
    "masculine": "/audio/pt-pt/masculine-97919de7c4178552.mp3"
  },
  "Onde é a paragem?": {
    "feminine": "/audio/pt-pt/feminine-10aed179aaec9c67.mp3",
    "masculine": "/audio/pt-pt/masculine-5f817c50e825c38b.mp3"
  },
  "Quero ida e volta": {
    "feminine": "/audio/pt-pt/feminine-e7e954ac76d8b885.mp3",
    "masculine": "/audio/pt-pt/masculine-b544a8f5adbe71eb.mp3"
  },
  "O quarto está pronto?": {
    "feminine": "/audio/pt-pt/feminine-65227580a6f6d49c.mp3",
    "masculine": "/audio/pt-pt/masculine-ba94146339e32239.mp3"
  },
  "Qual é a palavra-passe?": {
    "feminine": "/audio/pt-pt/feminine-aa9d4ca0f0c24663.mp3",
    "masculine": "/audio/pt-pt/masculine-7c6fed28902625aa.mp3"
  },
  "Preciso de uma toalha": {
    "feminine": "/audio/pt-pt/feminine-5e7f3d157086fb87.mp3",
    "masculine": "/audio/pt-pt/masculine-c585ea94c663f545.mp3"
  },
  "A que horas é o pequeno-almoço?": {
    "feminine": "/audio/pt-pt/feminine-a27d6b36b9bdce71.mp3",
    "masculine": "/audio/pt-pt/masculine-ad8197a1f7c73170.mp3"
  },
  "Está bom tempo": {
    "feminine": "/audio/pt-pt/feminine-7476a5796b8d93ef.mp3",
    "masculine": "/audio/pt-pt/masculine-5134e992fc52c2c2.mp3"
  },
  "Está a chover": {
    "feminine": "/audio/pt-pt/feminine-3d9ffe64565945bc.mp3",
    "masculine": "/audio/pt-pt/masculine-94c234d709fd88c0.mp3"
  },
  "Hoje está frio": {
    "feminine": "/audio/pt-pt/feminine-eb606de1cfa6c790.mp3",
    "masculine": "/audio/pt-pt/masculine-7d8691d090e49d16.mp3"
  },
  "Amanhã vai estar sol": {
    "feminine": "/audio/pt-pt/feminine-6841986d6d3c1f5e.mp3",
    "masculine": "/audio/pt-pt/masculine-69951cffd97df208.mp3"
  },
  "Leve um casaco": {
    "feminine": "/audio/pt-pt/feminine-5ef60de6e82f716b.mp3",
    "masculine": "/audio/pt-pt/masculine-740eef8a0eb1ce66.mp3"
  },
  "Gosto de música": {
    "feminine": "/audio/pt-pt/feminine-30ad28206a91aea1.mp3",
    "masculine": "/audio/pt-pt/masculine-aaef9a201d9456cc.mp3"
  },
  "Gosto de ler": {
    "feminine": "/audio/pt-pt/feminine-afa8d0632d1f24f7.mp3",
    "masculine": "/audio/pt-pt/masculine-21274f8167b94e84.mp3"
  },
  "Jogo futebol": {
    "feminine": "/audio/pt-pt/feminine-40e19383366e759d.mp3",
    "masculine": "/audio/pt-pt/masculine-9d1f6786d6db96df.mp3"
  },
  "Vejo filmes": {
    "feminine": "/audio/pt-pt/feminine-f3b9dca3830648aa.mp3",
    "masculine": "/audio/pt-pt/masculine-917be085214329e9.mp3"
  },
  "O que gosta de fazer?": {
    "feminine": "/audio/pt-pt/feminine-2ca5139e3c38acb8.mp3",
    "masculine": "/audio/pt-pt/masculine-9cb1d0acffb0f319.mp3"
  },
  "Trabalho num escritório": {
    "feminine": "/audio/pt-pt/feminine-d6ce921739180810.mp3",
    "masculine": "/audio/pt-pt/masculine-d9d769b24fec27d0.mp3"
  },
  "Estudo português": {
    "feminine": "/audio/pt-pt/feminine-423edcdaf9c97de9.mp3",
    "masculine": "/audio/pt-pt/masculine-dba00f838a93c93a.mp3"
  },
  "Qual é a sua profissão?": {
    "feminine": "/audio/pt-pt/feminine-fa3aef302292cde1.mp3",
    "masculine": "/audio/pt-pt/masculine-4d612b782fef94b6.mp3"
  },
  "Sou estudante": {
    "feminine": "/audio/pt-pt/feminine-75b8e744d9d6d923.mp3",
    "masculine": "/audio/pt-pt/masculine-cd524aa5abda0f45.mp3"
  },
  "Trabalho de manhã": {
    "feminine": "/audio/pt-pt/feminine-899fd77855d0f2af.mp3",
    "masculine": "/audio/pt-pt/masculine-70858b750672f607.mp3"
  },
  "Não me sinto bem": {
    "feminine": "/audio/pt-pt/feminine-53d059a34aee0e77.mp3",
    "masculine": "/audio/pt-pt/masculine-53d23ba0bd84b4f2.mp3"
  },
  "Dói-me a cabeça": {
    "feminine": "/audio/pt-pt/feminine-6a97a4947cfda281.mp3",
    "masculine": "/audio/pt-pt/masculine-7d66e204d1135ad0.mp3"
  },
  "Preciso de uma farmácia": {
    "feminine": "/audio/pt-pt/feminine-fb48adbbae46db37.mp3",
    "masculine": "/audio/pt-pt/masculine-f5cd52e1fbe19db2.mp3"
  },
  "Tem alguma alergia?": {
    "feminine": "/audio/pt-pt/feminine-f19f050a1767e4f6.mp3",
    "masculine": "/audio/pt-pt/masculine-b09d7e2e962de82d.mp3"
  },
  "Quero marcar uma consulta": {
    "feminine": "/audio/pt-pt/feminine-0f7171441ccae625.mp3",
    "masculine": "/audio/pt-pt/masculine-513c56bc9a150406.mp3"
  },
  "Quer tomar um café?": {
    "feminine": "/audio/pt-pt/feminine-a4ba2e3c9d85b54e.mp3",
    "masculine": "/audio/pt-pt/masculine-ef4d24f3be002b3e.mp3"
  },
  "Sim, com prazer": {
    "feminine": "/audio/pt-pt/feminine-a2397d439ad11457.mp3",
    "masculine": "/audio/pt-pt/masculine-d486135c8b1b4cdf.mp3"
  },
  "A que horas?": {
    "feminine": "/audio/pt-pt/feminine-e3c5f80277a1c4e9.mp3",
    "masculine": "/audio/pt-pt/masculine-124fc2e27e128e9f.mp3"
  },
  "Encontramo-nos às três": {
    "feminine": "/audio/pt-pt/feminine-0588679a1dc92785.mp3",
    "masculine": "/audio/pt-pt/masculine-3119eb3791248faa.mp3"
  },
  "Até logo": {
    "feminine": "/audio/pt-pt/feminine-c41a11d9014c1ffd.mp3",
    "masculine": "/audio/pt-pt/masculine-e38b85d72651f2f8.mp3"
  },
  "Olá, chamo-me Maria": {
    "feminine": "/audio/pt-pt/feminine-1f4921d66c926169.mp3",
    "masculine": "/audio/pt-pt/masculine-3131756c61fe92cb.mp3"
  },
  "Queria um café, por favor": {
    "feminine": "/audio/pt-pt/feminine-1b99f1ded690993e.mp3",
    "masculine": "/audio/pt-pt/masculine-2b19c3380ab5ea7a.mp3"
  },
  "Muito obrigado pela ajuda": {
    "feminine": "/audio/pt-pt/feminine-1a3bef80c620d59f.mp3",
    "masculine": "/audio/pt-pt/masculine-b6d44efa829d2f70.mp3"
  },
  "Olá, bom dia.": {
    "feminine": "/audio/pt-pt/feminine-d06fb594b33b4505.mp3",
    "masculine": "/audio/pt-pt/masculine-4d712e99321e74cd.mp3"
  },
  "Boa tarde / Boa noite.": {
    "feminine": "/audio/pt-pt/feminine-2ba382aec8b99a9c.mp3",
    "masculine": "/audio/pt-pt/masculine-b15174c95a440de1.mp3"
  },
  "Tudo bem, obrigado/a.": {
    "feminine": "/audio/pt-pt/feminine-78d9c8f3b470f3b5.mp3",
    "masculine": "/audio/pt-pt/masculine-998f0cc33ef1dc2e.mp3"
  },
  "Por favor / Se faz favor.": {
    "feminine": "/audio/pt-pt/feminine-e41986f1d3c0e927.mp3",
    "masculine": "/audio/pt-pt/masculine-bb9ff6eb577d8a0e.mp3"
  },
  "De nada.": {
    "feminine": "/audio/pt-pt/feminine-50f6428a20b8b6e7.mp3",
    "masculine": "/audio/pt-pt/masculine-ea453ce0e81c9fea.mp3"
  },
  "Chamo-me [nome].": {
    "feminine": "/audio/pt-pt/feminine-1ee3b60205f68b62.mp3",
    "masculine": "/audio/pt-pt/masculine-396a11134bac0fc1.mp3"
  },
  "Prazer em conhecê-lo/a.": {
    "feminine": "/audio/pt-pt/feminine-9c90f2ccfb36a94b.mp3",
    "masculine": "/audio/pt-pt/masculine-9ef9bb8d11f7ef18.mp3"
  },
  "Desculpe.": {
    "feminine": "/audio/pt-pt/feminine-c6a71aad4b3bccc3.mp3",
    "masculine": "/audio/pt-pt/masculine-9f97717bb8346065.mp3"
  },
  "Fala inglês?": {
    "feminine": "/audio/pt-pt/feminine-a10e21ff4b4361d0.mp3",
    "masculine": "/audio/pt-pt/masculine-5a23140b15925d02.mp3"
  },
  "Não percebo.": {
    "feminine": "/audio/pt-pt/feminine-d8d1bb246f4bf567.mp3",
    "masculine": "/audio/pt-pt/masculine-69abb63ade43c378.mp3"
  },
  "Pode repetir, por favor?": {
    "feminine": "/audio/pt-pt/feminine-5b071781588c880d.mp3",
    "masculine": "/audio/pt-pt/masculine-6db8c14452de9d04.mp3"
  },
  "Como se diz isto em português?": {
    "feminine": "/audio/pt-pt/feminine-91e40ce50f5c8454.mp3",
    "masculine": "/audio/pt-pt/masculine-b0c5a03bc06f7c3d.mp3"
  },
  "Onde fica o metro / a casa de banho?": {
    "feminine": "/audio/pt-pt/feminine-cf0cb1518b195fbf.mp3",
    "masculine": "/audio/pt-pt/masculine-a5a6c748447ccea7.mp3"
  },
  "A conta, por favor.": {
    "feminine": "/audio/pt-pt/feminine-13dd38fe23c7dced.mp3",
    "masculine": "/audio/pt-pt/masculine-637c26efb7c0f889.mp3"
  },
  "Queria um café, por favor.": {
    "feminine": "/audio/pt-pt/feminine-7661b718b54fb68f.mp3",
    "masculine": "/audio/pt-pt/masculine-30c4ef6ccb2c86b8.mp3"
  },
  "Onde posso comprar bilhetes?": {
    "feminine": "/audio/pt-pt/feminine-4bd1a4622972ee7a.mp3",
    "masculine": "/audio/pt-pt/masculine-6035135818b47b8f.mp3"
  },
  "Está aberto / fechado?": {
    "feminine": "/audio/pt-pt/feminine-06199ddb1dcfae15.mp3",
    "masculine": "/audio/pt-pt/masculine-f2924d9dbcc6fab7.mp3"
  },
  "Adeus, até amanhã.": {
    "feminine": "/audio/pt-pt/feminine-9e30a856d4fbc2d7.mp3",
    "masculine": "/audio/pt-pt/masculine-89af1212069ae9d1.mp3"
  },
  "Já moro em Portugal há seis meses.": {
    "feminine": "/audio/pt-pt/feminine-81c4f857d3369715.mp3",
    "masculine": "/audio/pt-pt/masculine-189b5001ba184da8.mp3"
  },
  "Estou a tentar aprender português, mas ainda é difícil.": {
    "feminine": "/audio/pt-pt/feminine-d2281a18d556e139.mp3",
    "masculine": "/audio/pt-pt/masculine-ef4a40438b69d4f2.mp3"
  },
  "O que é que me recomenda fazer por aqui?": {
    "feminine": "/audio/pt-pt/feminine-d2b833cff818aa2e.mp3",
    "masculine": "/audio/pt-pt/masculine-d50eb5f86cab0fc9.mp3"
  },
  "Combinado, encontramo-nos às oito horas.": {
    "feminine": "/audio/pt-pt/feminine-696d20edbad15cd9.mp3",
    "masculine": "/audio/pt-pt/masculine-e19b3d792dcfa68f.mp3"
  },
  "Fiquei muito contente por o/a ver hoje.": {
    "feminine": "/audio/pt-pt/feminine-ebdabf7bc26b68be.mp3",
    "masculine": "/audio/pt-pt/masculine-fb0cd9d024fbf6cd.mp3"
  },
  "Sabe se há alguma farmácia ou supermercado por perto?": {
    "feminine": "/audio/pt-pt/feminine-db879832a805a2bf.mp3",
    "masculine": "/audio/pt-pt/masculine-c6b77addce7f3e30.mp3"
  },
  "Queria marcar uma consulta / uma mesa para amanhã.": {
    "feminine": "/audio/pt-pt/feminine-4683378070bce355.mp3",
    "masculine": "/audio/pt-pt/masculine-01f32167b23dfac5.mp3"
  },
  "Aceitam pagamento com cartão ou tem de ser em dinheiro?": {
    "feminine": "/audio/pt-pt/feminine-e61cbc3d7ac4479b.mp3",
    "masculine": "/audio/pt-pt/masculine-fdea85c681a2142d.mp3"
  },
  "Pode dizer-me onde fica a paragem de autocarro mais próxima?": {
    "feminine": "/audio/pt-pt/feminine-60fe5488b5ae0d2a.mp3",
    "masculine": "/audio/pt-pt/masculine-9a128feb1dc1b30d.mp3"
  },
  "Disseram-me que este restaurante era muito bom.": {
    "feminine": "/audio/pt-pt/feminine-2ff5e049b2e6a80f.mp3",
    "masculine": "/audio/pt-pt/masculine-4d56a0061a093e77.mp3"
  },
  "Desculpe o atraso, houve muito trânsito no caminho.": {
    "feminine": "/audio/pt-pt/feminine-a80c03ff778a5efc.mp3",
    "masculine": "/audio/pt-pt/masculine-7f19c1f14954f8b3.mp3"
  },
  "O meu telemóvel ficou sem bateria, pode ajudar-me?": {
    "feminine": "/audio/pt-pt/feminine-114e9b3a290001b2.mp3",
    "masculine": "/audio/pt-pt/masculine-ab1c0e2ad7d81267.mp3"
  },
  "Acho que me perdi, pode mostrar-me o caminho no mapa?": {
    "feminine": "/audio/pt-pt/feminine-f62be210da7510a9.mp3",
    "masculine": "/audio/pt-pt/masculine-08ae33d81d55d1d8.mp3"
  },
  "Há algum problema com o meu pedido, falta aqui um prato.": {
    "feminine": "/audio/pt-pt/feminine-a33e11e0ef0847eb.mp3",
    "masculine": "/audio/pt-pt/masculine-073add39bab63b16.mp3"
  },
  "Acho que vai chover mais tarde, é melhor levar o guarda-chuva.": {
    "feminine": "/audio/pt-pt/feminine-570c93018d9f425e.mp3",
    "masculine": "/audio/pt-pt/masculine-b0fbedfb9c1aefba.mp3"
  },
  "Não sei se concordo com isso, mas compreendo o teu ponto.": {
    "feminine": "/audio/pt-pt/feminine-2ca28b16d28c8f4c.mp3",
    "masculine": "/audio/pt-pt/masculine-9b0ff80e0f6ad6f2.mp3"
  },
  "No próximo fim de semana gostava de ir passear a Sintra.": {
    "feminine": "/audio/pt-pt/feminine-d3901efcb05f63ad.mp3",
    "masculine": "/audio/pt-pt/masculine-4b128e6b15f1273e.mp3"
  },
  "Diverti-me imenso e a comida estava deliciosa.": {
    "feminine": "/audio/pt-pt/feminine-8e5bd31742858bbf.mp3",
    "masculine": "/audio/pt-pt/masculine-558e72d55e041b84.mp3"
  },
  "Se eu tiver tempo amanhã, passo por tua casa.": {
    "feminine": "/audio/pt-pt/feminine-61acfcd5abbe63aa.mp3",
    "masculine": "/audio/pt-pt/masculine-b002962e9a9fa96e.mp3"
  },
  "Tenho de ir embora agora, senão vou perder o comboio.": {
    "feminine": "/audio/pt-pt/feminine-e3c245157f43aeaf.mp3",
    "masculine": "/audio/pt-pt/masculine-8f5a662b6b7f4ce8.mp3"
  },
  "Gostaria que revíssemos os termos do contrato antes de avançarmos.": {
    "feminine": "/audio/pt-pt/feminine-55bf536ae7dde016.mp3",
    "masculine": "/audio/pt-pt/masculine-14f64a289efc2f13.mp3"
  },
  "Caso surja algum imprevisto, entrarei em contacto imediatamente.": {
    "feminine": "/audio/pt-pt/feminine-a5bc3d7e0e07854d.mp3",
    "masculine": "/audio/pt-pt/masculine-8e73807909aec6e8.mp3"
  },
  "Ficou acordado que a entrega seria feita até ao final da semana.": {
    "feminine": "/audio/pt-pt/feminine-9cd715905bf7fe31.mp3",
    "masculine": "/audio/pt-pt/masculine-e436cdc744af98e0.mp3"
  },
  "Precisamos de otimizar este processo para evitar desperdício de tempo.": {
    "feminine": "/audio/pt-pt/feminine-a30528d17a78deca.mp3",
    "masculine": "/audio/pt-pt/masculine-5949c9e75036b86e.mp3"
  },
  "Se eu soubesse que ia demorar tanto, teria saído mais cedo.": {
    "feminine": "/audio/pt-pt/feminine-a93a36e520d58eb1.mp3",
    "masculine": "/audio/pt-pt/masculine-aa70afd542af85b4.mp3"
  },
  "Agradeço desde já a sua disponibilidade para reunir comigo.": {
    "feminine": "/audio/pt-pt/feminine-6b9ae3166274b7f6.mp3",
    "masculine": "/audio/pt-pt/masculine-288b4f3c13c5e47a.mp3"
  },
  "Desde que faças a tua parte, não haverá qualquer problema.": {
    "feminine": "/audio/pt-pt/feminine-fe0636bc558fc555.mp3",
    "masculine": "/audio/pt-pt/masculine-029df97223c5acf1.mp3"
  },
  "Por mais que tente, ainda me custa habituar ao sotaque daqui.": {
    "feminine": "/audio/pt-pt/feminine-a37d943d3d050d9b.mp3",
    "masculine": "/audio/pt-pt/masculine-50ed3fe43cbeaac1.mp3"
  },
  "Oxalá a situação se resolva o mais rapidamente possível.": {
    "feminine": "/audio/pt-pt/feminine-d48d8d7c7b8a82ea.mp3",
    "masculine": "/audio/pt-pt/masculine-5318b3aeb15ab3f7.mp3"
  },
  "A menos que surjam objeções, daremos o projeto por concluído.": {
    "feminine": "/audio/pt-pt/feminine-650693b6900e6a30.mp3",
    "masculine": "/audio/pt-pt/masculine-04f0eafb25d07165.mp3"
  },
  "Temos de encarar os factos, as coisas não correram como planeado.": {
    "feminine": "/audio/pt-pt/feminine-f937a06f0157eb7e.mp3",
    "masculine": "/audio/pt-pt/masculine-2ac75235b12abdae.mp3"
  },
  "Vale mais prevenir do que remediar, por isso convém ter cuidado.": {
    "feminine": "/audio/pt-pt/feminine-59e8bf0ace74cacf.mp3",
    "masculine": "/audio/pt-pt/masculine-af9a8dcb71a4c887.mp3"
  },
  "No que toca a este assunto, prefiro manter-me neutro.": {
    "feminine": "/audio/pt-pt/feminine-1668628ce811da05.mp3",
    "masculine": "/audio/pt-pt/masculine-9d418a76b2e1e580.mp3"
  },
  "Isso não faz o menor sentido, estás a ver as coisas ao contrário.": {
    "feminine": "/audio/pt-pt/feminine-84dfa82c9ac64243.mp3",
    "masculine": "/audio/pt-pt/masculine-e269144fdcc1e781.mp3"
  },
  "Não vale a pena chorar sobre o leite derramado, temos de avançar.": {
    "feminine": "/audio/pt-pt/feminine-affde35946075ae6.mp3",
    "masculine": "/audio/pt-pt/masculine-b4735a2a5a133040.mp3"
  },
  "Estás a dar graxa ao chefe para ver se consegues uma promoção?": {
    "feminine": "/audio/pt-pt/feminine-cb7deef301c5305f.mp3",
    "masculine": "/audio/pt-pt/masculine-aa3d386a10ab9607.mp3"
  },
  "Ficámos a ver navios, porque o fornecedor falhou o prazo.": {
    "feminine": "/audio/pt-pt/feminine-03a1207590bbb627.mp3",
    "masculine": "/audio/pt-pt/masculine-3517bfef8fd9639e.mp3"
  },
  "Não fiques a engolir sapos, diz claramente o que pensas.": {
    "feminine": "/audio/pt-pt/feminine-648c800771a55f23.mp3",
    "masculine": "/audio/pt-pt/masculine-97ab209f77c8c8a8.mp3"
  },
  "Aquela conversa foi só para inglês ver, nada vai mudar realmente.": {
    "feminine": "/audio/pt-pt/feminine-cee63f40c580f2a3.mp3",
    "masculine": "/audio/pt-pt/masculine-9579b43a7e3ffb5f.mp3"
  },
  "Bom": {
    "feminine": "/audio/pt-pt/feminine-c7fed88041fc739d.mp3",
    "masculine": "/audio/pt-pt/masculine-badae5e70540eccc.mp3"
  },
  "dia": {
    "feminine": "/audio/pt-pt/feminine-0be3fa0b85b4e5a1.mp3",
    "masculine": "/audio/pt-pt/masculine-a0e939939f168e32.mp3"
  },
  "Calma, não ponhas a carroça à frente dos bois.": {
    "feminine": "/audio/pt-pt/feminine-fdd4f3bbf81acd9b.mp3",
    "masculine": "/audio/pt-pt/masculine-b410646d9df95658.mp3"
  },
  "Boa": {
    "feminine": "/audio/pt-pt/feminine-2bd2a3482e02f10d.mp3",
    "masculine": "/audio/pt-pt/masculine-3141dd1f66dacb89.mp3"
  },
  "tarde": {
    "feminine": "/audio/pt-pt/feminine-c311ecdf4b0e5f67.mp3",
    "masculine": "/audio/pt-pt/masculine-f9ead12bf995f803.mp3"
  },
  "noite": {
    "feminine": "/audio/pt-pt/feminine-76da2424ffdc0ff9.mp3",
    "masculine": "/audio/pt-pt/masculine-136791076c89dcfb.mp3"
  },
  "Como": {
    "feminine": "/audio/pt-pt/feminine-04776504d09a61dc.mp3",
    "masculine": "/audio/pt-pt/masculine-50f7faa781ee8f20.mp3"
  },
  "está": {
    "feminine": "/audio/pt-pt/feminine-ad05a62688df1f7e.mp3",
    "masculine": "/audio/pt-pt/masculine-2c18b14a1d087ad9.mp3"
  },
  "Por": {
    "feminine": "/audio/pt-pt/feminine-79dee414a4db0904.mp3",
    "masculine": "/audio/pt-pt/masculine-5dfe719a5f144870.mp3"
  },
  "favor": {
    "feminine": "/audio/pt-pt/feminine-fcbd7d79a7b160a9.mp3",
    "masculine": "/audio/pt-pt/masculine-cd507aaff3dfd750.mp3"
  },
  "De": {
    "feminine": "/audio/pt-pt/feminine-e9b968af51f48df6.mp3",
    "masculine": "/audio/pt-pt/masculine-62c7de23c294d775.mp3"
  },
  "nada": {
    "feminine": "/audio/pt-pt/feminine-8b77259692f21ed1.mp3",
    "masculine": "/audio/pt-pt/masculine-18b5c899e859861c.mp3"
  },
  "Queria": {
    "feminine": "/audio/pt-pt/feminine-c35c9c7cae0100f3.mp3",
    "masculine": "/audio/pt-pt/masculine-ae66f606c8c7f950.mp3"
  },
  "por": {
    "feminine": "/audio/pt-pt/feminine-494b76309d9d86e9.mp3",
    "masculine": "/audio/pt-pt/masculine-c82acc29581cdaf6.mp3"
  },
  "e": {
    "feminine": "/audio/pt-pt/feminine-ec82bf7882828edc.mp3",
    "masculine": "/audio/pt-pt/masculine-53e9617de1cca24a.mp3"
  },
  "A": {
    "feminine": "/audio/pt-pt/feminine-fc0ef17f3f29fee6.mp3",
    "masculine": "/audio/pt-pt/masculine-f04efe2a1f39b74b.mp3"
  },
  "conta": {
    "feminine": "/audio/pt-pt/feminine-6389f6c9951b439e.mp3",
    "masculine": "/audio/pt-pt/masculine-ed072c99262c515a.mp3"
  },
  "sumo": {
    "feminine": "/audio/pt-pt/feminine-8d98525465289e73.mp3",
    "masculine": "/audio/pt-pt/masculine-1dc7ec0ca689fd69.mp3"
  },
  "de": {
    "feminine": "/audio/pt-pt/feminine-0b919c1c567b7337.mp3",
    "masculine": "/audio/pt-pt/masculine-ac0ee9ef2c94d3c6.mp3"
  },
  "nata": {
    "feminine": "/audio/pt-pt/feminine-d247696c1efd8d93.mp3",
    "masculine": "/audio/pt-pt/masculine-c1fa2a949ba9d9ae.mp3"
  },
  "laranja": {
    "feminine": "/audio/pt-pt/feminine-c1fce38f86e77557.mp3",
    "masculine": "/audio/pt-pt/masculine-6f5ed1f65bc95a5c.mp3"
  },
  "pastel": {
    "feminine": "/audio/pt-pt/feminine-fd3b150b680c2004.mp3",
    "masculine": "/audio/pt-pt/masculine-538a0789f6aaa54c.mp3"
  },
  "sem": {
    "feminine": "/audio/pt-pt/feminine-93138a0263733c33.mp3",
    "masculine": "/audio/pt-pt/masculine-a3bb10ed4a2dd32e.mp3"
  },
  "açúcar": {
    "feminine": "/audio/pt-pt/feminine-9cb39bf82926fded.mp3",
    "masculine": "/audio/pt-pt/masculine-357969be41c1b6b1.mp3"
  },
  "Onde": {
    "feminine": "/audio/pt-pt/feminine-4f81e0b6d6627924.mp3",
    "masculine": "/audio/pt-pt/masculine-261763eee8f3cac2.mp3"
  },
  "fica": {
    "feminine": "/audio/pt-pt/feminine-e00c0ce25ff4c59f.mp3",
    "masculine": "/audio/pt-pt/masculine-5ea547f7dbfd47ac.mp3"
  },
  "À": {
    "feminine": "/audio/pt-pt/feminine-d12abfb56df460c5.mp3",
    "masculine": "/audio/pt-pt/masculine-df2b245340bf915e.mp3"
  },
  "a": {
    "feminine": "/audio/pt-pt/feminine-7f3645454e265a8a.mp3",
    "masculine": "/audio/pt-pt/masculine-126c1d7a0b7b278e.mp3"
  },
  "estação": {
    "feminine": "/audio/pt-pt/feminine-0961b92e661b2130.mp3",
    "masculine": "/audio/pt-pt/masculine-e8b132e33749e3df.mp3"
  },
  "esquerda": {
    "feminine": "/audio/pt-pt/feminine-854535fad32d356c.mp3",
    "masculine": "/audio/pt-pt/masculine-b7a9ed863a93569a.mp3"
  },
  "Tenho": {
    "feminine": "/audio/pt-pt/feminine-5e3ea93341a31237.mp3",
    "masculine": "/audio/pt-pt/masculine-8a7e00118feebb8a.mp3"
  },
  "direita": {
    "feminine": "/audio/pt-pt/feminine-8165642ef05247a5.mp3",
    "masculine": "/audio/pt-pt/masculine-6979f0957c0335aa.mp3"
  },
  "uma": {
    "feminine": "/audio/pt-pt/feminine-b1be72144f7cdf9e.mp3",
    "masculine": "/audio/pt-pt/masculine-cc78b0bfabb65aa0.mp3"
  },
  "reserva": {
    "feminine": "/audio/pt-pt/feminine-f9115187f0836ac2.mp3",
    "masculine": "/audio/pt-pt/masculine-dba9d5f87833a7ca.mp3"
  },
  "O": {
    "feminine": "/audio/pt-pt/feminine-55a012bb3a72b442.mp3",
    "masculine": "/audio/pt-pt/masculine-6cd45cd9869bda66.mp3"
  },
  "paragem": {
    "feminine": "/audio/pt-pt/feminine-15626bf90b27e77b.mp3",
    "masculine": "/audio/pt-pt/masculine-15272cece719ba95.mp3"
  },
  "metro": {
    "feminine": "/audio/pt-pt/feminine-3656b11af9cb4953.mp3",
    "masculine": "/audio/pt-pt/masculine-83c5d04d6aff1d82.mp3"
  },
  "Em": {
    "feminine": "/audio/pt-pt/feminine-81f9c178fcddf197.mp3",
    "masculine": "/audio/pt-pt/masculine-52e4cb0ab84d0d5f.mp3"
  },
  "frente": {
    "feminine": "/audio/pt-pt/feminine-235ef7abfe20db79.mp3",
    "masculine": "/audio/pt-pt/masculine-9b5095395b678695.mp3"
  },
  "Quanto": {
    "feminine": "/audio/pt-pt/feminine-7e5986ea21beca7a.mp3",
    "masculine": "/audio/pt-pt/masculine-b6a9002d6b829d21.mp3"
  },
  "custa": {
    "feminine": "/audio/pt-pt/feminine-e17bb61f8c66d4d0.mp3",
    "masculine": "/audio/pt-pt/masculine-6b96b83d8da4a217.mp3"
  },
  "o": {
    "feminine": "/audio/pt-pt/feminine-b2b7508d17b066e5.mp3",
    "masculine": "/audio/pt-pt/masculine-bc78ce40e9afe545.mp3"
  },
  "Preciso": {
    "feminine": "/audio/pt-pt/feminine-ef559f66075602f4.mp3",
    "masculine": "/audio/pt-pt/masculine-ec154dff8abbc2ae.mp3"
  },
  "táxi": {
    "feminine": "/audio/pt-pt/feminine-ca28b42e4d668f2f.mp3",
    "masculine": "/audio/pt-pt/masculine-a48a53747ba6178e.mp3"
  },
  "bilhete": {
    "feminine": "/audio/pt-pt/feminine-a85765bdb53193ce.mp3",
    "masculine": "/audio/pt-pt/masculine-9d23e406a1b129b3.mp3"
  },
  "Chamo-me": {
    "feminine": "/audio/pt-pt/feminine-7a42736761ff1f11.mp3",
    "masculine": "/audio/pt-pt/masculine-eb9be627acb568c2.mp3"
  },
  "Ana": {
    "feminine": "/audio/pt-pt/feminine-b5f742b764e61a13.mp3",
    "masculine": "/audio/pt-pt/masculine-54235227aa1cb83c.mp3"
  },
  "se": {
    "feminine": "/audio/pt-pt/feminine-31d02dcd4cff119f.mp3",
    "masculine": "/audio/pt-pt/masculine-55e2dd8aafbeb169.mp3"
  },
  "chama": {
    "feminine": "/audio/pt-pt/feminine-b9ade1f6e58c02aa.mp3",
    "masculine": "/audio/pt-pt/masculine-b04048251300cb35.mp3"
  },
  "Sou": {
    "feminine": "/audio/pt-pt/feminine-16e7b2f41f982542.mp3",
    "masculine": "/audio/pt-pt/masculine-9f212f8f5c34d672.mp3"
  },
  "Inglaterra": {
    "feminine": "/audio/pt-pt/feminine-e29e3edbbf646f55.mp3",
    "masculine": "/audio/pt-pt/masculine-50787c21acf25f40.mp3"
  },
  "Muito": {
    "feminine": "/audio/pt-pt/feminine-69e9d5c745ea4870.mp3",
    "masculine": "/audio/pt-pt/masculine-e39b083bb2eb6b20.mp3"
  },
  "prazer": {
    "feminine": "/audio/pt-pt/feminine-5837be2cb933cbde.mp3",
    "masculine": "/audio/pt-pt/masculine-00c4a066c8dbaa32.mp3"
  },
  "E": {
    "feminine": "/audio/pt-pt/feminine-9950688509e5b388.mp3",
    "masculine": "/audio/pt-pt/masculine-b2c482be4b616f61.mp3"
  },
  "você": {
    "feminine": "/audio/pt-pt/feminine-2e313bcb4927615a.mp3",
    "masculine": "/audio/pt-pt/masculine-d6469264fa67a887.mp3"
  },
  "obrigado": {
    "feminine": "/audio/pt-pt/feminine-b16a942831489e9b.mp3",
    "masculine": "/audio/pt-pt/masculine-4372c122f1f15d96.mp3"
  },
  "Com": {
    "feminine": "/audio/pt-pt/feminine-520b8349f4b28f88.mp3",
    "masculine": "/audio/pt-pt/masculine-057944bdded1f0ad.mp3"
  },
  "licença": {
    "feminine": "/audio/pt-pt/feminine-1884c7a0a804a00d.mp3",
    "masculine": "/audio/pt-pt/masculine-d8f0a39e770c2043.mp3"
  },
  "Peço": {
    "feminine": "/audio/pt-pt/feminine-b4d82951e478883e.mp3",
    "masculine": "/audio/pt-pt/masculine-f48404d8f48ac374.mp3"
  },
  "desculpa": {
    "feminine": "/audio/pt-pt/feminine-e0d182624a6d7c31.mp3",
    "masculine": "/audio/pt-pt/masculine-8e9c6cbbcd96820b.mp3"
  },
  "Não": {
    "feminine": "/audio/pt-pt/feminine-ba287e43c0fe2a7c.mp3",
    "masculine": "/audio/pt-pt/masculine-713e125f32c3ac77.mp3"
  },
  "mal": {
    "feminine": "/audio/pt-pt/feminine-fdf93dfe4a2c0482.mp3",
    "masculine": "/audio/pt-pt/masculine-aa2ec48f0b625945.mp3"
  },
  "faz": {
    "feminine": "/audio/pt-pt/feminine-9fadeee2f5d816cf.mp3",
    "masculine": "/audio/pt-pt/masculine-23b94aa051777e39.mp3"
  },
  "Que": {
    "feminine": "/audio/pt-pt/feminine-a47006f201431318.mp3",
    "masculine": "/audio/pt-pt/masculine-f99a87d8fbca5749.mp3"
  },
  "horas": {
    "feminine": "/audio/pt-pt/feminine-df684141fc161f7c.mp3",
    "masculine": "/audio/pt-pt/masculine-d88a41754978a0d0.mp3"
  },
  "É": {
    "feminine": "/audio/pt-pt/feminine-0b5686b87df6a0cc.mp3",
    "masculine": "/audio/pt-pt/masculine-6ae042d7fc8323a9.mp3"
  },
  "hora": {
    "feminine": "/audio/pt-pt/feminine-1ba35a0770767c27.mp3",
    "masculine": "/audio/pt-pt/masculine-b9f384f9f1e56b2f.mp3"
  },
  "são": {
    "feminine": "/audio/pt-pt/feminine-76f8727401c2ad96.mp3",
    "masculine": "/audio/pt-pt/masculine-b3b87b1abfe2eaa2.mp3"
  },
  "São": {
    "feminine": "/audio/pt-pt/feminine-beb351eb4f0de437.mp3",
    "masculine": "/audio/pt-pt/masculine-5fc7e31004665856.mp3"
  },
  "duas": {
    "feminine": "/audio/pt-pt/feminine-92860129b588b6bf.mp3",
    "masculine": "/audio/pt-pt/masculine-3b5f788ef9c5e173.mp3"
  },
  "Hoje": {
    "feminine": "/audio/pt-pt/feminine-ddf8919e497460cf.mp3",
    "masculine": "/audio/pt-pt/masculine-797f8fca3da96f0d.mp3"
  },
  "segunda-feira": {
    "feminine": "/audio/pt-pt/feminine-ef8c3dcbc827afce.mp3",
    "masculine": "/audio/pt-pt/masculine-39e7b314d5bf63c7.mp3"
  },
  "Amanhã": {
    "feminine": "/audio/pt-pt/feminine-3179b36530c7cc4e.mp3",
    "masculine": "/audio/pt-pt/masculine-075f82d17835b3ed.mp3"
  },
  "manhã": {
    "feminine": "/audio/pt-pt/feminine-5fad0d0fbe75b12c.mp3",
    "masculine": "/audio/pt-pt/masculine-b014396066c9ed16.mp3"
  },
  "Esta": {
    "feminine": "/audio/pt-pt/feminine-f6dc1ef90026b4d7.mp3",
    "masculine": "/audio/pt-pt/masculine-c8cdda14fb2c1baf.mp3"
  },
  "minha": {
    "feminine": "/audio/pt-pt/feminine-4603907e30f71ed7.mp3",
    "masculine": "/audio/pt-pt/masculine-b7a3f57e68fce49d.mp3"
  },
  "mãe": {
    "feminine": "/audio/pt-pt/feminine-be547abf13776b39.mp3",
    "masculine": "/audio/pt-pt/masculine-f67174fc9b298db3.mp3"
  },
  "Este": {
    "feminine": "/audio/pt-pt/feminine-94e49f2efba59e7a.mp3",
    "masculine": "/audio/pt-pt/masculine-8769837a7ecc9f79.mp3"
  },
  "meu": {
    "feminine": "/audio/pt-pt/feminine-8c9a81cab41a6422.mp3",
    "masculine": "/audio/pt-pt/masculine-d0572cdba393eef1.mp3"
  },
  "pai": {
    "feminine": "/audio/pt-pt/feminine-02605a92b47a9f48.mp3",
    "masculine": "/audio/pt-pt/masculine-6654f5bd956ea767.mp3"
  },
  "irmã": {
    "feminine": "/audio/pt-pt/feminine-c84585452731980b.mp3",
    "masculine": "/audio/pt-pt/masculine-4c3d94a11b82000e.mp3"
  },
  "irmão": {
    "feminine": "/audio/pt-pt/feminine-5aebcb065dee18ae.mp3",
    "masculine": "/audio/pt-pt/masculine-4ac7a87f9bd81296.mp3"
  },
  "família": {
    "feminine": "/audio/pt-pt/feminine-2763a3db0b90688d.mp3",
    "masculine": "/audio/pt-pt/masculine-a19bf0a9bbedd8ed.mp3"
  },
  "cozinha": {
    "feminine": "/audio/pt-pt/feminine-2d258ee789769462.mp3",
    "masculine": "/audio/pt-pt/masculine-81cb8cc2f5a1d6d8.mp3"
  },
  "quarto": {
    "feminine": "/audio/pt-pt/feminine-7aff8c85595158f6.mp3",
    "masculine": "/audio/pt-pt/masculine-ca711cf95995f619.mp3"
  },
  "pequeno": {
    "feminine": "/audio/pt-pt/feminine-c9922c95974a575d.mp3",
    "masculine": "/audio/pt-pt/masculine-68e431d63d5a379c.mp3"
  },
  "banho": {
    "feminine": "/audio/pt-pt/feminine-19bad45159335592.mp3",
    "masculine": "/audio/pt-pt/masculine-076b840f221cd952.mp3"
  },
  "casa": {
    "feminine": "/audio/pt-pt/feminine-44c64471efcd5b5a.mp3",
    "masculine": "/audio/pt-pt/masculine-ee3cb8247fe70b6c.mp3"
  },
  "chave": {
    "feminine": "/audio/pt-pt/feminine-82f935f90b022c5b.mp3",
    "masculine": "/audio/pt-pt/masculine-05a35af3a3128710.mp3"
  },
  "é": {
    "feminine": "/audio/pt-pt/feminine-2b95c992348bf283.mp3",
    "masculine": "/audio/pt-pt/masculine-a4f27029326113c6.mp3"
  },
  "na": {
    "feminine": "/audio/pt-pt/feminine-d524a1102c47a638.mp3",
    "masculine": "/audio/pt-pt/masculine-e907cb7cb335e1fc.mp3"
  },
  "mesa": {
    "feminine": "/audio/pt-pt/feminine-c0f49c08f4e8872f.mp3",
    "masculine": "/audio/pt-pt/masculine-a062d2af571b1c8c.mp3"
  },
  "às": {
    "feminine": "/audio/pt-pt/feminine-4e8ca5ef98ae86f3.mp3",
    "masculine": "/audio/pt-pt/masculine-61c61138c3f181d8.mp3"
  },
  "Acordo": {
    "feminine": "/audio/pt-pt/feminine-1d1b3956fd9d6a60.mp3",
    "masculine": "/audio/pt-pt/masculine-770472e393d2907c.mp3"
  },
  "Tomo": {
    "feminine": "/audio/pt-pt/feminine-85b984f0bf812262.mp3",
    "masculine": "/audio/pt-pt/masculine-22e494d0ed5980ed.mp3"
  },
  "Vou": {
    "feminine": "/audio/pt-pt/feminine-116646fdfc919cde.mp3",
    "masculine": "/audio/pt-pt/masculine-20140737cfaac87a.mp3"
  },
  "pequeno-almoço": {
    "feminine": "/audio/pt-pt/feminine-a33b5e093356b988.mp3",
    "masculine": "/audio/pt-pt/masculine-73b9a5d375d66080.mp3"
  },
  "para": {
    "feminine": "/audio/pt-pt/feminine-dc7e2f1e086d602e.mp3",
    "masculine": "/audio/pt-pt/masculine-b5829888f4aea7e0.mp3"
  },
  "Janto": {
    "feminine": "/audio/pt-pt/feminine-4f4d227f4894acb8.mp3",
    "masculine": "/audio/pt-pt/masculine-26391f620917a305.mp3"
  },
  "trabalho": {
    "feminine": "/audio/pt-pt/feminine-dd1fc3e9da582d19.mp3",
    "masculine": "/audio/pt-pt/masculine-6c2312f85f3916f9.mp3"
  },
  "Deito-me": {
    "feminine": "/audio/pt-pt/feminine-78847c5dd02a74a7.mp3",
    "masculine": "/audio/pt-pt/masculine-214fdb70d80e6e9b.mp3"
  },
  "cedo": {
    "feminine": "/audio/pt-pt/feminine-c2c501cb358b4dda.mp3",
    "masculine": "/audio/pt-pt/masculine-787e2aefa52214cc.mp3"
  },
  "Tem": {
    "feminine": "/audio/pt-pt/feminine-fd62f4304d50fdc4.mp3",
    "masculine": "/audio/pt-pt/masculine-a78c2debb40071ef.mp3"
  },
  "isto": {
    "feminine": "/audio/pt-pt/feminine-f2178a07e0cf2915.mp3",
    "masculine": "/audio/pt-pt/masculine-dcc019e28d90d1d3.mp3"
  },
  "tamanho": {
    "feminine": "/audio/pt-pt/feminine-160ae4d7f7c94366.mp3",
    "masculine": "/audio/pt-pt/masculine-84e2eb0e4dd2df3f.mp3"
  },
  "maior": {
    "feminine": "/audio/pt-pt/feminine-7be9b56d461080f5.mp3",
    "masculine": "/audio/pt-pt/masculine-069c085859ce1eba.mp3"
  },
  "Quero": {
    "feminine": "/audio/pt-pt/feminine-d156165a7e8cf070.mp3",
    "masculine": "/audio/pt-pt/masculine-4814076f1263ef4b.mp3"
  },
  "azul": {
    "feminine": "/audio/pt-pt/feminine-c5b7a4065a1a56f7.mp3",
    "masculine": "/audio/pt-pt/masculine-cb310961dda2e8f5.mp3"
  },
  "experimentar": {
    "feminine": "/audio/pt-pt/feminine-7f35bfba54a4da01.mp3",
    "masculine": "/audio/pt-pt/masculine-a394b4a8863c9739.mp3"
  },
  "Posso": {
    "feminine": "/audio/pt-pt/feminine-473326182245b312.mp3",
    "masculine": "/audio/pt-pt/masculine-3a95cb5ae1ca75b5.mp3"
  },
  "Pago": {
    "feminine": "/audio/pt-pt/feminine-5cf280027c4947cc.mp3",
    "masculine": "/audio/pt-pt/masculine-2e961f2941d5cb50.mp3"
  },
  "centro": {
    "feminine": "/audio/pt-pt/feminine-abf722e3f9c07bde.mp3",
    "masculine": "/audio/pt-pt/masculine-87bebac4f0df38a5.mp3"
  },
  "com": {
    "feminine": "/audio/pt-pt/feminine-e87ab1fe6ed6b8b3.mp3",
    "masculine": "/audio/pt-pt/masculine-522afa91f5e7037e.mp3"
  },
  "Siga": {
    "feminine": "/audio/pt-pt/feminine-2032c179a83a32b1.mp3",
    "masculine": "/audio/pt-pt/masculine-ae9e2bed06c4ab5c.mp3"
  },
  "cartão": {
    "feminine": "/audio/pt-pt/feminine-188e90cb2bdc164e.mp3",
    "masculine": "/audio/pt-pt/masculine-56f09ac6f6f1e642.mp3"
  },
  "Vire": {
    "feminine": "/audio/pt-pt/feminine-0164751a8408c769.mp3",
    "masculine": "/audio/pt-pt/masculine-f8297268a119e0ab.mp3"
  },
  "em": {
    "feminine": "/audio/pt-pt/feminine-43a2b6c7d4d106a1.mp3",
    "masculine": "/audio/pt-pt/masculine-a49e207b91cd6c1d.mp3"
  },
  "à": {
    "feminine": "/audio/pt-pt/feminine-256ac73c5493a4b8.mp3",
    "masculine": "/audio/pt-pt/masculine-a9a18d7c49c25ab5.mp3"
  },
  "perto": {
    "feminine": "/audio/pt-pt/feminine-c7e06f0389237402.mp3",
    "masculine": "/audio/pt-pt/masculine-0bd99a65e34b726d.mp3"
  },
  "Um": {
    "feminine": "/audio/pt-pt/feminine-a8113c692a311a60.mp3",
    "masculine": "/audio/pt-pt/masculine-541660692e5ffe2d.mp3"
  },
  "daqui": {
    "feminine": "/audio/pt-pt/feminine-943af1c12ba31974.mp3",
    "masculine": "/audio/pt-pt/masculine-5d5957266ef27709.mp3"
  },
  "Lisboa": {
    "feminine": "/audio/pt-pt/feminine-bb67cf59b7abc4df.mp3",
    "masculine": "/audio/pt-pt/masculine-25a3bf3c9d2f3e0b.mp3"
  },
  "que": {
    "feminine": "/audio/pt-pt/feminine-8b3aaea7a1a9ce6b.mp3",
    "masculine": "/audio/pt-pt/masculine-37e15a15fcef88a3.mp3"
  },
  "parte": {
    "feminine": "/audio/pt-pt/feminine-48aa6f6eca37ba9e.mp3",
    "masculine": "/audio/pt-pt/masculine-5a6e8aad4d387632.mp3"
  },
  "comboio": {
    "feminine": "/audio/pt-pt/feminine-9b6660d32540e565.mp3",
    "masculine": "/audio/pt-pt/masculine-95ce95336e4657b0.mp3"
  },
  "este": {
    "feminine": "/audio/pt-pt/feminine-d3a3c53943a519a9.mp3",
    "masculine": "/audio/pt-pt/masculine-1f700af62593975c.mp3"
  },
  "volta": {
    "feminine": "/audio/pt-pt/feminine-3b00bf74b5a568c0.mp3",
    "masculine": "/audio/pt-pt/masculine-a0c2df8dce5fa3b8.mp3"
  },
  "ida": {
    "feminine": "/audio/pt-pt/feminine-a7488696034cc788.mp3",
    "masculine": "/audio/pt-pt/masculine-96a6cf94ebd36b75.mp3"
  },
  "pronto": {
    "feminine": "/audio/pt-pt/feminine-a982be14866ddcb7.mp3",
    "masculine": "/audio/pt-pt/masculine-6164fe9f20161203.mp3"
  },
  "Qual": {
    "feminine": "/audio/pt-pt/feminine-936b7dc947a75aff.mp3",
    "masculine": "/audio/pt-pt/masculine-34b6b047ff10623a.mp3"
  },
  "toalha": {
    "feminine": "/audio/pt-pt/feminine-fc5ae6eb5b72332f.mp3",
    "masculine": "/audio/pt-pt/masculine-3011bbfda082c725.mp3"
  },
  "palavra-passe": {
    "feminine": "/audio/pt-pt/feminine-f6c18e6b6dfd35b7.mp3",
    "masculine": "/audio/pt-pt/masculine-4b2d5d9468857af3.mp3"
  },
  "bom": {
    "feminine": "/audio/pt-pt/feminine-53e102d4bd419531.mp3",
    "masculine": "/audio/pt-pt/masculine-c97417d7b1c41dec.mp3"
  },
  "tempo": {
    "feminine": "/audio/pt-pt/feminine-5d8fd80cd56d3e3c.mp3",
    "masculine": "/audio/pt-pt/masculine-542c0f744ebf562d.mp3"
  },
  "chover": {
    "feminine": "/audio/pt-pt/feminine-ff5b13f3a7c58d94.mp3",
    "masculine": "/audio/pt-pt/masculine-db7f6df3d0ff6137.mp3"
  },
  "Está": {
    "feminine": "/audio/pt-pt/feminine-89b0a1004736a9d0.mp3",
    "masculine": "/audio/pt-pt/masculine-99d5737e6ec1983b.mp3"
  },
  "frio": {
    "feminine": "/audio/pt-pt/feminine-84cefbca2e375f8f.mp3",
    "masculine": "/audio/pt-pt/masculine-cd7d2aced1fd9aac.mp3"
  },
  "estar": {
    "feminine": "/audio/pt-pt/feminine-c0641fbb7e55fa39.mp3",
    "masculine": "/audio/pt-pt/masculine-f460f2331e1726e8.mp3"
  },
  "vai": {
    "feminine": "/audio/pt-pt/feminine-cdbdfebececedebc.mp3",
    "masculine": "/audio/pt-pt/masculine-6a9f4cfd84bd1b7a.mp3"
  },
  "sol": {
    "feminine": "/audio/pt-pt/feminine-986f54ee3ac1b6bb.mp3",
    "masculine": "/audio/pt-pt/masculine-acddc927403de18c.mp3"
  },
  "Leve": {
    "feminine": "/audio/pt-pt/feminine-cdd4dc00d71d18a7.mp3",
    "masculine": "/audio/pt-pt/masculine-4d02504ceb79d846.mp3"
  },
  "casaco": {
    "feminine": "/audio/pt-pt/feminine-64525feb16a49938.mp3",
    "masculine": "/audio/pt-pt/masculine-eb4ef62338b8faaf.mp3"
  },
  "música": {
    "feminine": "/audio/pt-pt/feminine-91a842ff8024d7b0.mp3",
    "masculine": "/audio/pt-pt/masculine-38054a7f90a35dd5.mp3"
  },
  "Gosto": {
    "feminine": "/audio/pt-pt/feminine-6cc44b347cfe84dc.mp3",
    "masculine": "/audio/pt-pt/masculine-7dc6514c3ae88854.mp3"
  },
  "ler": {
    "feminine": "/audio/pt-pt/feminine-fa42a1e0d767e828.mp3",
    "masculine": "/audio/pt-pt/masculine-92aef410538c7aef.mp3"
  },
  "Jogo": {
    "feminine": "/audio/pt-pt/feminine-9fae0bac4c0c5742.mp3",
    "masculine": "/audio/pt-pt/masculine-40b04e722bea4fc0.mp3"
  },
  "futebol": {
    "feminine": "/audio/pt-pt/feminine-5bbb85a503e4d6f0.mp3",
    "masculine": "/audio/pt-pt/masculine-5acca489db5924d3.mp3"
  },
  "filmes": {
    "feminine": "/audio/pt-pt/feminine-c29cdba34c988f72.mp3",
    "masculine": "/audio/pt-pt/masculine-c80d974685fa0123.mp3"
  },
  "Vejo": {
    "feminine": "/audio/pt-pt/feminine-61299883214d43f0.mp3",
    "masculine": "/audio/pt-pt/masculine-d77ee6206f77941f.mp3"
  },
  "fazer": {
    "feminine": "/audio/pt-pt/feminine-69e6fecb84097403.mp3",
    "masculine": "/audio/pt-pt/masculine-f9f182e4147477d1.mp3"
  },
  "num": {
    "feminine": "/audio/pt-pt/feminine-87605186ee85fc26.mp3",
    "masculine": "/audio/pt-pt/masculine-ce566a8349b85a61.mp3"
  },
  "Trabalho": {
    "feminine": "/audio/pt-pt/feminine-293ddf37486b7f03.mp3",
    "masculine": "/audio/pt-pt/masculine-c633f64cff9ac3b4.mp3"
  },
  "gosta": {
    "feminine": "/audio/pt-pt/feminine-40a7afcd2f342a38.mp3",
    "masculine": "/audio/pt-pt/masculine-3f5c6f9229fadfef.mp3"
  },
  "Estudo": {
    "feminine": "/audio/pt-pt/feminine-97506e2fee70108d.mp3",
    "masculine": "/audio/pt-pt/masculine-d39eda84d5b94800.mp3"
  },
  "escritório": {
    "feminine": "/audio/pt-pt/feminine-1c3db2d95d4a7007.mp3",
    "masculine": "/audio/pt-pt/masculine-4e2aeadaa8a2fab1.mp3"
  },
  "português": {
    "feminine": "/audio/pt-pt/feminine-43707343a69ec616.mp3",
    "masculine": "/audio/pt-pt/masculine-01926ad289bed450.mp3"
  },
  "sua": {
    "feminine": "/audio/pt-pt/feminine-4ba062d3e66c00ee.mp3",
    "masculine": "/audio/pt-pt/masculine-729bb52bf7046b68.mp3"
  },
  "estudante": {
    "feminine": "/audio/pt-pt/feminine-393498e7970b02d1.mp3",
    "masculine": "/audio/pt-pt/masculine-c0815ca3ffc6cc20.mp3"
  },
  "profissão": {
    "feminine": "/audio/pt-pt/feminine-c8a3eb9a69d22bd7.mp3",
    "masculine": "/audio/pt-pt/masculine-986e0342538659a9.mp3"
  },
  "me": {
    "feminine": "/audio/pt-pt/feminine-29f6cb50cbc70592.mp3",
    "masculine": "/audio/pt-pt/masculine-349c3528c0c60b7f.mp3"
  },
  "bem": {
    "feminine": "/audio/pt-pt/feminine-b0f9a8911866c9a5.mp3",
    "masculine": "/audio/pt-pt/masculine-4552ac854e84caa7.mp3"
  },
  "Dói-me": {
    "feminine": "/audio/pt-pt/feminine-610858a7f5a9b639.mp3",
    "masculine": "/audio/pt-pt/masculine-5e67fbef3931ee38.mp3"
  },
  "sinto": {
    "feminine": "/audio/pt-pt/feminine-ca66bd04d31ce00b.mp3",
    "masculine": "/audio/pt-pt/masculine-7967c47502c40106.mp3"
  },
  "cabeça": {
    "feminine": "/audio/pt-pt/feminine-1d81616b484c7f99.mp3",
    "masculine": "/audio/pt-pt/masculine-ceeebc6c0a86b22d.mp3"
  },
  "farmácia": {
    "feminine": "/audio/pt-pt/feminine-3fea25294b9100ba.mp3",
    "masculine": "/audio/pt-pt/masculine-83526ac472df10a0.mp3"
  },
  "alguma": {
    "feminine": "/audio/pt-pt/feminine-1dbd65db045f1509.mp3",
    "masculine": "/audio/pt-pt/masculine-07b39ad2f5f32211.mp3"
  },
  "alergia": {
    "feminine": "/audio/pt-pt/feminine-e60b5e92faaa0082.mp3",
    "masculine": "/audio/pt-pt/masculine-98927bacb5c8780a.mp3"
  },
  "consulta": {
    "feminine": "/audio/pt-pt/feminine-ae12b4a2adfbb83e.mp3",
    "masculine": "/audio/pt-pt/masculine-0e006c549c33f369.mp3"
  },
  "marcar": {
    "feminine": "/audio/pt-pt/feminine-99446bfbc25ff37b.mp3",
    "masculine": "/audio/pt-pt/masculine-b87bc28c2e724db2.mp3"
  },
  "Quer": {
    "feminine": "/audio/pt-pt/feminine-ed74ec9891cdbcfc.mp3",
    "masculine": "/audio/pt-pt/masculine-86b057ce1d5a13ee.mp3"
  },
  "café": {
    "feminine": "/audio/pt-pt/feminine-9230eccc850d14a0.mp3",
    "masculine": "/audio/pt-pt/masculine-ce3b906dc49e083a.mp3"
  },
  "tomar": {
    "feminine": "/audio/pt-pt/feminine-12962d12e27f9e4b.mp3",
    "masculine": "/audio/pt-pt/masculine-a7fb6de01789079e.mp3"
  },
  "Sim": {
    "feminine": "/audio/pt-pt/feminine-9f830c269e3c049f.mp3",
    "masculine": "/audio/pt-pt/masculine-0c6978d3b942dc7e.mp3"
  },
  "Encontramo-nos": {
    "feminine": "/audio/pt-pt/feminine-ddb65efef5840985.mp3",
    "masculine": "/audio/pt-pt/masculine-462704d130389596.mp3"
  },
  "Até": {
    "feminine": "/audio/pt-pt/feminine-eb41e47bd398c64a.mp3",
    "masculine": "/audio/pt-pt/masculine-8cfd06fe3d300407.mp3"
  },
  "logo": {
    "feminine": "/audio/pt-pt/feminine-21a8f4b7a1114a70.mp3",
    "masculine": "/audio/pt-pt/masculine-1149741b0df2ac89.mp3"
  },
  "Maria": {
    "feminine": "/audio/pt-pt/feminine-2bb1c02057cf47e5.mp3",
    "masculine": "/audio/pt-pt/masculine-b3da2bb4f0d278cd.mp3"
  },
  "pela": {
    "feminine": "/audio/pt-pt/feminine-c2f4572b243fd508.mp3",
    "masculine": "/audio/pt-pt/masculine-28bdbe43819593cd.mp3"
  },
  "chamo-me": {
    "feminine": "/audio/pt-pt/feminine-8bbb026bfa1a989f.mp3",
    "masculine": "/audio/pt-pt/masculine-958ba7d484d6c049.mp3"
  },
  "ajuda": {
    "feminine": "/audio/pt-pt/feminine-1b09ebfe7dd8ce51.mp3",
    "masculine": "/audio/pt-pt/masculine-3ce7ac926e543556.mp3"
  },
  "Tudo": {
    "feminine": "/audio/pt-pt/feminine-c8b3236ac3e62f6b.mp3",
    "masculine": "/audio/pt-pt/masculine-90cf6841deedb16d.mp3"
  },
  "Se": {
    "feminine": "/audio/pt-pt/feminine-9d0a7be5b851c761.mp3",
    "masculine": "/audio/pt-pt/masculine-135b020915eb480d.mp3"
  },
  "nome": {
    "feminine": "/audio/pt-pt/feminine-79db1b7256be20ca.mp3",
    "masculine": "/audio/pt-pt/masculine-1eebcc7556f64b8f.mp3"
  },
  "Prazer": {
    "feminine": "/audio/pt-pt/feminine-04651b9a0bc69cd0.mp3",
    "masculine": "/audio/pt-pt/masculine-89b1a4f85e3e6007.mp3"
  },
  "conhecê-lo": {
    "feminine": "/audio/pt-pt/feminine-6e2c8dfa623d736c.mp3",
    "masculine": "/audio/pt-pt/masculine-08e028554f1db1e8.mp3"
  },
  "Desculpe": {
    "feminine": "/audio/pt-pt/feminine-b17c59d42b3219c1.mp3",
    "masculine": "/audio/pt-pt/masculine-6bb5e3dede5f0212.mp3"
  },
  "Fala": {
    "feminine": "/audio/pt-pt/feminine-4ffe33a4bf6118e3.mp3",
    "masculine": "/audio/pt-pt/masculine-c9f19520847d633d.mp3"
  },
  "inglês": {
    "feminine": "/audio/pt-pt/feminine-c00fc69087db513b.mp3",
    "masculine": "/audio/pt-pt/masculine-e48bc9808770026a.mp3"
  },
  "percebo": {
    "feminine": "/audio/pt-pt/feminine-c33dd9f312835581.mp3",
    "masculine": "/audio/pt-pt/masculine-f6f5636a50966fdd.mp3"
  },
  "repetir": {
    "feminine": "/audio/pt-pt/feminine-b7210b17cbf1ee4f.mp3",
    "masculine": "/audio/pt-pt/masculine-170f91ec82e1fc02.mp3"
  },
  "Pode": {
    "feminine": "/audio/pt-pt/feminine-24af90a2b6b4112d.mp3",
    "masculine": "/audio/pt-pt/masculine-0bc4bce43edc3dd4.mp3"
  },
  "diz": {
    "feminine": "/audio/pt-pt/feminine-929ef6d9f609acdf.mp3",
    "masculine": "/audio/pt-pt/masculine-905f8a669804bea3.mp3"
  },
  "comprar": {
    "feminine": "/audio/pt-pt/feminine-f0fdb73bf8863d91.mp3",
    "masculine": "/audio/pt-pt/masculine-15063837eec1bcf3.mp3"
  },
  "bilhetes": {
    "feminine": "/audio/pt-pt/feminine-463f7bbd436af8e5.mp3",
    "masculine": "/audio/pt-pt/masculine-5aa1efc0fa3a0160.mp3"
  },
  "posso": {
    "feminine": "/audio/pt-pt/feminine-1af10ee33712196c.mp3",
    "masculine": "/audio/pt-pt/masculine-35e7a7888c255aea.mp3"
  },
  "aberto": {
    "feminine": "/audio/pt-pt/feminine-05aa453a65b08497.mp3",
    "masculine": "/audio/pt-pt/masculine-05e18970193d81e3.mp3"
  },
  "fechado": {
    "feminine": "/audio/pt-pt/feminine-4cd58af42f69c93f.mp3",
    "masculine": "/audio/pt-pt/masculine-f94e42fc75d2011d.mp3"
  },
  "até": {
    "feminine": "/audio/pt-pt/feminine-58350dc9f70d14ca.mp3",
    "masculine": "/audio/pt-pt/masculine-3d7cd7635ac576f8.mp3"
  },
  "amanhã": {
    "feminine": "/audio/pt-pt/feminine-426fe7ff18be0ba9.mp3",
    "masculine": "/audio/pt-pt/masculine-24cbec6a95b5bf74.mp3"
  },
  "Já": {
    "feminine": "/audio/pt-pt/feminine-8432c4c5922c7834.mp3",
    "masculine": "/audio/pt-pt/masculine-9d4d5469acc154dd.mp3"
  },
  "moro": {
    "feminine": "/audio/pt-pt/feminine-f9135e286158ab46.mp3",
    "masculine": "/audio/pt-pt/masculine-d4e2261bcfc8a6dd.mp3"
  },
  "Portugal": {
    "feminine": "/audio/pt-pt/feminine-aca30ce29334f611.mp3",
    "masculine": "/audio/pt-pt/masculine-c6b72befcc0ed6a5.mp3"
  },
  "há": {
    "feminine": "/audio/pt-pt/feminine-2106d673bfdfb6c5.mp3",
    "masculine": "/audio/pt-pt/masculine-d49ec30b4f9e69d9.mp3"
  },
  "meses": {
    "feminine": "/audio/pt-pt/feminine-444e9d69aebf9d50.mp3",
    "masculine": "/audio/pt-pt/masculine-c68e9d377ae4001b.mp3"
  },
  "Estou": {
    "feminine": "/audio/pt-pt/feminine-4b73fb69f1860ac5.mp3",
    "masculine": "/audio/pt-pt/masculine-ef7127b24822a958.mp3"
  },
  "tentar": {
    "feminine": "/audio/pt-pt/feminine-4db022f8dc7ca65a.mp3",
    "masculine": "/audio/pt-pt/masculine-1a603f0811f58eea.mp3"
  },
  "aprender": {
    "feminine": "/audio/pt-pt/feminine-552af6b87cc84948.mp3",
    "masculine": "/audio/pt-pt/masculine-d554f8e2828e86d2.mp3"
  },
  "mas": {
    "feminine": "/audio/pt-pt/feminine-76d05f7f4e9409c8.mp3",
    "masculine": "/audio/pt-pt/masculine-6935bea248eb399c.mp3"
  },
  "ainda": {
    "feminine": "/audio/pt-pt/feminine-b151df047de2be85.mp3",
    "masculine": "/audio/pt-pt/masculine-bca2c348def70fcf.mp3"
  },
  "difícil": {
    "feminine": "/audio/pt-pt/feminine-b487ae3d9c181a4f.mp3",
    "masculine": "/audio/pt-pt/masculine-d46bb66397786fa9.mp3"
  },
  "recomenda": {
    "feminine": "/audio/pt-pt/feminine-6ecbbca224f14f39.mp3",
    "masculine": "/audio/pt-pt/masculine-a123c8beb0778dad.mp3"
  },
  "aqui": {
    "feminine": "/audio/pt-pt/feminine-7025fe92f22d225c.mp3",
    "masculine": "/audio/pt-pt/masculine-539844f346925f35.mp3"
  },
  "Combinado": {
    "feminine": "/audio/pt-pt/feminine-f67a5dfd72e7bf47.mp3",
    "masculine": "/audio/pt-pt/masculine-f2fd5e67b23313de.mp3"
  },
  "encontramo-nos": {
    "feminine": "/audio/pt-pt/feminine-513b2084654b4fe7.mp3",
    "masculine": "/audio/pt-pt/masculine-4d7f8960035b8b7f.mp3"
  },
  "Fiquei": {
    "feminine": "/audio/pt-pt/feminine-4380fffdc2475eac.mp3",
    "masculine": "/audio/pt-pt/masculine-5a9fd1a2b86f3ef7.mp3"
  },
  "muito": {
    "feminine": "/audio/pt-pt/feminine-31646e539893a157.mp3",
    "masculine": "/audio/pt-pt/masculine-151c7393f52a9f28.mp3"
  },
  "contente": {
    "feminine": "/audio/pt-pt/feminine-064fc51f9b279e8f.mp3",
    "masculine": "/audio/pt-pt/masculine-36001b8ad0180db5.mp3"
  },
  "ver": {
    "feminine": "/audio/pt-pt/feminine-c13a0a487dfbd22e.mp3",
    "masculine": "/audio/pt-pt/masculine-eaa6d046005e779e.mp3"
  },
  "hoje": {
    "feminine": "/audio/pt-pt/feminine-dd5e6b8f739b6493.mp3",
    "masculine": "/audio/pt-pt/masculine-a63d5bb52aba2149.mp3"
  },
  "Sabe": {
    "feminine": "/audio/pt-pt/feminine-ab77819c7a559956.mp3",
    "masculine": "/audio/pt-pt/masculine-b1c143964b9f000e.mp3"
  },
  "ou": {
    "feminine": "/audio/pt-pt/feminine-ba8a633a800d5fae.mp3",
    "masculine": "/audio/pt-pt/masculine-86213877f227e667.mp3"
  },
  "supermercado": {
    "feminine": "/audio/pt-pt/feminine-6897469bc4b7a63f.mp3",
    "masculine": "/audio/pt-pt/masculine-3ec6b72849e44891.mp3"
  },
  "Aceitam": {
    "feminine": "/audio/pt-pt/feminine-ae4a26c9135b470f.mp3",
    "masculine": "/audio/pt-pt/masculine-d4667fb146efaf92.mp3"
  },
  "pagamento": {
    "feminine": "/audio/pt-pt/feminine-40f38fdd60215038.mp3",
    "masculine": "/audio/pt-pt/masculine-a1df31b939d20593.mp3"
  },
  "tem": {
    "feminine": "/audio/pt-pt/feminine-42e0ee4dcd92047e.mp3",
    "masculine": "/audio/pt-pt/masculine-5df07d3a24789f9d.mp3"
  },
  "ser": {
    "feminine": "/audio/pt-pt/feminine-2833167bd2a7f5cb.mp3",
    "masculine": "/audio/pt-pt/masculine-b6ec3c715bd2a704.mp3"
  },
  "dinheiro": {
    "feminine": "/audio/pt-pt/feminine-3fc75add285076c2.mp3",
    "masculine": "/audio/pt-pt/masculine-193c462a5e606b84.mp3"
  },
  "onde": {
    "feminine": "/audio/pt-pt/feminine-cb065928e9902f6f.mp3",
    "masculine": "/audio/pt-pt/masculine-0779fd4409909dfe.mp3"
  },
  "dizer-me": {
    "feminine": "/audio/pt-pt/feminine-b6d9ee6b6a22c983.mp3",
    "masculine": "/audio/pt-pt/masculine-d032c8963a013a1a.mp3"
  },
  "autocarro": {
    "feminine": "/audio/pt-pt/feminine-49e773d7bc69515f.mp3",
    "masculine": "/audio/pt-pt/masculine-26a62034f3dbd4a8.mp3"
  },
  "mais": {
    "feminine": "/audio/pt-pt/feminine-4486a4bdd83c073b.mp3",
    "masculine": "/audio/pt-pt/masculine-66125986d595427b.mp3"
  },
  "próxima": {
    "feminine": "/audio/pt-pt/feminine-c28b644579815077.mp3",
    "masculine": "/audio/pt-pt/masculine-bdb9ac20fc78386a.mp3"
  },
  "Disseram-me": {
    "feminine": "/audio/pt-pt/feminine-610fa81890d5878d.mp3",
    "masculine": "/audio/pt-pt/masculine-a3a68d5a597f4d40.mp3"
  },
  "era": {
    "feminine": "/audio/pt-pt/feminine-d8f8bfea449b3782.mp3",
    "masculine": "/audio/pt-pt/masculine-e4eb0f1b574c072b.mp3"
  },
  "restaurante": {
    "feminine": "/audio/pt-pt/feminine-0243d5ed4b5e5ce4.mp3",
    "masculine": "/audio/pt-pt/masculine-730d78f979065c70.mp3"
  },
  "houve": {
    "feminine": "/audio/pt-pt/feminine-66e60d94069da70b.mp3",
    "masculine": "/audio/pt-pt/masculine-d8545acd7eecec68.mp3"
  },
  "atraso": {
    "feminine": "/audio/pt-pt/feminine-d45008e3d158dee0.mp3",
    "masculine": "/audio/pt-pt/masculine-d1f46d3de68d6fcc.mp3"
  },
  "trânsito": {
    "feminine": "/audio/pt-pt/feminine-0f2a665f4e7e4eac.mp3",
    "masculine": "/audio/pt-pt/masculine-a94ccaad7ae5f06d.mp3"
  },
  "no": {
    "feminine": "/audio/pt-pt/feminine-b2ebaf15a1850c97.mp3",
    "masculine": "/audio/pt-pt/masculine-5b5a2971daa083bf.mp3"
  },
  "caminho": {
    "feminine": "/audio/pt-pt/feminine-979463a4d344f498.mp3",
    "masculine": "/audio/pt-pt/masculine-2e0f4e7750612cd8.mp3"
  },
  "telemóvel": {
    "feminine": "/audio/pt-pt/feminine-94d56977b0d99b16.mp3",
    "masculine": "/audio/pt-pt/masculine-b67ee1b1f56072cf.mp3"
  },
  "ficou": {
    "feminine": "/audio/pt-pt/feminine-f195bf719fa7a2e6.mp3",
    "masculine": "/audio/pt-pt/masculine-a11390b6d2d36489.mp3"
  },
  "bateria": {
    "feminine": "/audio/pt-pt/feminine-44ecba622a7d2135.mp3",
    "masculine": "/audio/pt-pt/masculine-67b55ac6d8466a0d.mp3"
  },
  "pode": {
    "feminine": "/audio/pt-pt/feminine-a0c119bc059bc05c.mp3",
    "masculine": "/audio/pt-pt/masculine-64f6c462dbfc0c4c.mp3"
  },
  "ajudar-me": {
    "feminine": "/audio/pt-pt/feminine-3b84a43f85b3d8d2.mp3",
    "masculine": "/audio/pt-pt/masculine-4a18becb98d26b8d.mp3"
  },
  "Acho": {
    "feminine": "/audio/pt-pt/feminine-eea2b881a3674129.mp3",
    "masculine": "/audio/pt-pt/masculine-f584a680aca73753.mp3"
  },
  "mostrar-me": {
    "feminine": "/audio/pt-pt/feminine-4a309fa20d7adb2a.mp3",
    "masculine": "/audio/pt-pt/masculine-2b1c5d7889f28b67.mp3"
  },
  "perdi": {
    "feminine": "/audio/pt-pt/feminine-fce63200555b7bcb.mp3",
    "masculine": "/audio/pt-pt/masculine-9f2fa29c0c91c505.mp3"
  },
  "mapa": {
    "feminine": "/audio/pt-pt/feminine-2d287cef7f392850.mp3",
    "masculine": "/audio/pt-pt/masculine-d8ced12a14839e75.mp3"
  },
  "Há": {
    "feminine": "/audio/pt-pt/feminine-4847f6acb0419b71.mp3",
    "masculine": "/audio/pt-pt/masculine-28c509e1ddfa9ecc.mp3"
  },
  "algum": {
    "feminine": "/audio/pt-pt/feminine-bd71a5502b0e14b5.mp3",
    "masculine": "/audio/pt-pt/masculine-0f4990a44f931035.mp3"
  },
  "problema": {
    "feminine": "/audio/pt-pt/feminine-1e9155c10d3d6db0.mp3",
    "masculine": "/audio/pt-pt/masculine-eb4d56e8e65d9af3.mp3"
  },
  "pedido": {
    "feminine": "/audio/pt-pt/feminine-2908bab561d5b5ba.mp3",
    "masculine": "/audio/pt-pt/masculine-21ceddcf7c28d08a.mp3"
  },
  "falta": {
    "feminine": "/audio/pt-pt/feminine-831c71f8a8790174.mp3",
    "masculine": "/audio/pt-pt/masculine-97111d8517fac61d.mp3"
  },
  "melhor": {
    "feminine": "/audio/pt-pt/feminine-4ff33ab1b10ec54f.mp3",
    "masculine": "/audio/pt-pt/masculine-7a281c396d771167.mp3"
  },
  "prato": {
    "feminine": "/audio/pt-pt/feminine-1dd213557d4002e7.mp3",
    "masculine": "/audio/pt-pt/masculine-61e7868dcf829391.mp3"
  },
  "levar": {
    "feminine": "/audio/pt-pt/feminine-f8aa3116d2ba698b.mp3",
    "masculine": "/audio/pt-pt/masculine-f186c3d5cf00d908.mp3"
  },
  "guarda-chuva": {
    "feminine": "/audio/pt-pt/feminine-2883ebf93b60ae9b.mp3",
    "masculine": "/audio/pt-pt/masculine-49c378462d74e2eb.mp3"
  },
  "No": {
    "feminine": "/audio/pt-pt/feminine-e87bf06fcb784271.mp3",
    "masculine": "/audio/pt-pt/masculine-f36e9723d00c11e5.mp3"
  },
  "próximo": {
    "feminine": "/audio/pt-pt/feminine-0d3c0fd200fb5b0e.mp3",
    "masculine": "/audio/pt-pt/masculine-cb0128c1e35c7e2d.mp3"
  },
  "fim": {
    "feminine": "/audio/pt-pt/feminine-78cb7e120405b01d.mp3",
    "masculine": "/audio/pt-pt/masculine-93de90d9288e0930.mp3"
  },
  "gostava": {
    "feminine": "/audio/pt-pt/feminine-47682d9b0b0b22c4.mp3",
    "masculine": "/audio/pt-pt/masculine-bc6083d5c3b1f96f.mp3"
  },
  "semana": {
    "feminine": "/audio/pt-pt/feminine-8238b7570c76722e.mp3",
    "masculine": "/audio/pt-pt/masculine-0760582b1533cfe0.mp3"
  },
  "ir": {
    "feminine": "/audio/pt-pt/feminine-b08641e753a31b9a.mp3",
    "masculine": "/audio/pt-pt/masculine-3e4478973432f317.mp3"
  },
  "passear": {
    "feminine": "/audio/pt-pt/feminine-164da439a71cfe60.mp3",
    "masculine": "/audio/pt-pt/masculine-ee7cf7ab8b1a2aae.mp3"
  },
  "Sintra": {
    "feminine": "/audio/pt-pt/feminine-7964877d8a6e2421.mp3",
    "masculine": "/audio/pt-pt/masculine-4326d26f064e6400.mp3"
  },
  "Diverti-me": {
    "feminine": "/audio/pt-pt/feminine-96cd1e9b89876e73.mp3",
    "masculine": "/audio/pt-pt/masculine-017fe7616f23161e.mp3"
  },
  "imenso": {
    "feminine": "/audio/pt-pt/feminine-81e4a65b0cbec126.mp3",
    "masculine": "/audio/pt-pt/masculine-75ee1f3b41ee6ffe.mp3"
  },
  "estava": {
    "feminine": "/audio/pt-pt/feminine-df4c7134f1b73289.mp3",
    "masculine": "/audio/pt-pt/masculine-4954f0640aeec1bc.mp3"
  },
  "comida": {
    "feminine": "/audio/pt-pt/feminine-b04220fda37c4c35.mp3",
    "masculine": "/audio/pt-pt/masculine-7a525e329cf6ef01.mp3"
  },
  "deliciosa": {
    "feminine": "/audio/pt-pt/feminine-6eb137cdcde4d301.mp3",
    "masculine": "/audio/pt-pt/masculine-b19bba7cc6bd539b.mp3"
  },
  "eu": {
    "feminine": "/audio/pt-pt/feminine-34391a2f392ed475.mp3",
    "masculine": "/audio/pt-pt/masculine-340c0c224a72b10e.mp3"
  },
  "tiver": {
    "feminine": "/audio/pt-pt/feminine-95680bc9546094a3.mp3",
    "masculine": "/audio/pt-pt/masculine-52ab3202f259c1cd.mp3"
  },
  "passo": {
    "feminine": "/audio/pt-pt/feminine-8afc1d14f674444f.mp3",
    "masculine": "/audio/pt-pt/masculine-e7df4408f593befc.mp3"
  },
  "tua": {
    "feminine": "/audio/pt-pt/feminine-e1be336d24f89e12.mp3",
    "masculine": "/audio/pt-pt/masculine-daa6174d1d7c06fd.mp3"
  },
  "sei": {
    "feminine": "/audio/pt-pt/feminine-2627fe20e5dbef2c.mp3",
    "masculine": "/audio/pt-pt/masculine-c9dc9a1f7729b105.mp3"
  },
  "concordo": {
    "feminine": "/audio/pt-pt/feminine-082db778dbad6978.mp3",
    "masculine": "/audio/pt-pt/masculine-ab683eb0c808b6f6.mp3"
  },
  "isso": {
    "feminine": "/audio/pt-pt/feminine-832e11230c7d7a60.mp3",
    "masculine": "/audio/pt-pt/masculine-389ae94e8fb14ab8.mp3"
  },
  "teu": {
    "feminine": "/audio/pt-pt/feminine-a207bff5254ff0c1.mp3",
    "masculine": "/audio/pt-pt/masculine-414e720fde63e795.mp3"
  },
  "compreendo": {
    "feminine": "/audio/pt-pt/feminine-855b93df05a8ebd4.mp3",
    "masculine": "/audio/pt-pt/masculine-1a626050946e5386.mp3"
  },
  "ponto": {
    "feminine": "/audio/pt-pt/feminine-8ca55ab7acb8dd4c.mp3",
    "masculine": "/audio/pt-pt/masculine-9669d146721c2f27.mp3"
  },
  "embora": {
    "feminine": "/audio/pt-pt/feminine-ab03143d0629b6a8.mp3",
    "masculine": "/audio/pt-pt/masculine-292994b0c5083beb.mp3"
  },
  "agora": {
    "feminine": "/audio/pt-pt/feminine-333dad6d4e2b5201.mp3",
    "masculine": "/audio/pt-pt/masculine-ca93ec682c89378a.mp3"
  },
  "senão": {
    "feminine": "/audio/pt-pt/feminine-9a8053c9638d0a8d.mp3",
    "masculine": "/audio/pt-pt/masculine-c4d1da755373e54c.mp3"
  },
  "vou": {
    "feminine": "/audio/pt-pt/feminine-d3184c427beb93f9.mp3",
    "masculine": "/audio/pt-pt/masculine-8e2a01a704e1639f.mp3"
  },
  "perder": {
    "feminine": "/audio/pt-pt/feminine-5f44c1a3ce02db8e.mp3",
    "masculine": "/audio/pt-pt/masculine-11fd338a8edec175.mp3"
  },
  "Gostaria": {
    "feminine": "/audio/pt-pt/feminine-7182e3dfe999c8f4.mp3",
    "masculine": "/audio/pt-pt/masculine-fd34124fb61e7614.mp3"
  },
  "revíssemos": {
    "feminine": "/audio/pt-pt/feminine-371b635ee9de5c00.mp3",
    "masculine": "/audio/pt-pt/masculine-b3c3fb41b6c8d245.mp3"
  },
  "os": {
    "feminine": "/audio/pt-pt/feminine-8b81bdb4751d049b.mp3",
    "masculine": "/audio/pt-pt/masculine-59d246b18aa69a49.mp3"
  },
  "termos": {
    "feminine": "/audio/pt-pt/feminine-9459bffc6112375e.mp3",
    "masculine": "/audio/pt-pt/masculine-e06e346daef51f1e.mp3"
  },
  "do": {
    "feminine": "/audio/pt-pt/feminine-2baf3558e70745b5.mp3",
    "masculine": "/audio/pt-pt/masculine-1fcfb81cb5a6bbe4.mp3"
  },
  "contrato": {
    "feminine": "/audio/pt-pt/feminine-0d469cb8cfe5a23e.mp3",
    "masculine": "/audio/pt-pt/masculine-354868522c296b31.mp3"
  },
  "antes": {
    "feminine": "/audio/pt-pt/feminine-5f25d24f1f9fc02e.mp3",
    "masculine": "/audio/pt-pt/masculine-87408f543c5854fd.mp3"
  },
  "surja": {
    "feminine": "/audio/pt-pt/feminine-c7f082f3e62fb57f.mp3",
    "masculine": "/audio/pt-pt/masculine-5731accbb7e51576.mp3"
  },
  "Caso": {
    "feminine": "/audio/pt-pt/feminine-98a4a2e8593367c7.mp3",
    "masculine": "/audio/pt-pt/masculine-59e067718bb9446d.mp3"
  },
  "avançarmos": {
    "feminine": "/audio/pt-pt/feminine-4e236a618f0dd75d.mp3",
    "masculine": "/audio/pt-pt/masculine-4de5d99eefe3aa46.mp3"
  },
  "imprevisto": {
    "feminine": "/audio/pt-pt/feminine-d25ddd0d95b81eb2.mp3",
    "masculine": "/audio/pt-pt/masculine-61b0dc3a548de2e2.mp3"
  },
  "entrarei": {
    "feminine": "/audio/pt-pt/feminine-9a200c780c1e7ac3.mp3",
    "masculine": "/audio/pt-pt/masculine-5f77a6e8690ffbe3.mp3"
  },
  "contacto": {
    "feminine": "/audio/pt-pt/feminine-cb01daf1fd1532bb.mp3",
    "masculine": "/audio/pt-pt/masculine-056f4182e68cae95.mp3"
  },
  "imediatamente": {
    "feminine": "/audio/pt-pt/feminine-de467034ae4301a7.mp3",
    "masculine": "/audio/pt-pt/masculine-96ad8ddd3adb71b2.mp3"
  },
  "Ficou": {
    "feminine": "/audio/pt-pt/feminine-f08db1df9a66794b.mp3",
    "masculine": "/audio/pt-pt/masculine-7c58353ee23886b5.mp3"
  },
  "entrega": {
    "feminine": "/audio/pt-pt/feminine-165492c5dfe08b59.mp3",
    "masculine": "/audio/pt-pt/masculine-5f3e8245fee94ce1.mp3"
  },
  "acordado": {
    "feminine": "/audio/pt-pt/feminine-b201fe93b743c5d2.mp3",
    "masculine": "/audio/pt-pt/masculine-18eaff2e5a6a5bf5.mp3"
  },
  "seria": {
    "feminine": "/audio/pt-pt/feminine-d3490851bd27d32c.mp3",
    "masculine": "/audio/pt-pt/masculine-d29a82d68d13dd5c.mp3"
  },
  "feita": {
    "feminine": "/audio/pt-pt/feminine-88d4c4c2c5e7e5fe.mp3",
    "masculine": "/audio/pt-pt/masculine-d8b0eeca2301b4a0.mp3"
  },
  "final": {
    "feminine": "/audio/pt-pt/feminine-e206e2de44e28560.mp3",
    "masculine": "/audio/pt-pt/masculine-822ddf0839ad8fd9.mp3"
  },
  "ao": {
    "feminine": "/audio/pt-pt/feminine-d27e19f909f1f613.mp3",
    "masculine": "/audio/pt-pt/masculine-057425534e1fb8ca.mp3"
  },
  "da": {
    "feminine": "/audio/pt-pt/feminine-6670dee3c41c08a7.mp3",
    "masculine": "/audio/pt-pt/masculine-1777ad0d76b5e791.mp3"
  },
  "processo": {
    "feminine": "/audio/pt-pt/feminine-3936f6e122168f20.mp3",
    "masculine": "/audio/pt-pt/masculine-ca0f544ab0c5a5c6.mp3"
  },
  "Precisamos": {
    "feminine": "/audio/pt-pt/feminine-07e82219fab49b74.mp3",
    "masculine": "/audio/pt-pt/masculine-6fb5d54034606803.mp3"
  },
  "otimizar": {
    "feminine": "/audio/pt-pt/feminine-63ecfd89d6239bb6.mp3",
    "masculine": "/audio/pt-pt/masculine-9a5081dd4ce4737d.mp3"
  },
  "evitar": {
    "feminine": "/audio/pt-pt/feminine-758c86ef432902be.mp3",
    "masculine": "/audio/pt-pt/masculine-d0a2f8a3e647c4aa.mp3"
  },
  "Agradeço": {
    "feminine": "/audio/pt-pt/feminine-719fdd622eb38a56.mp3",
    "masculine": "/audio/pt-pt/masculine-2b544ac6e36d2f30.mp3"
  },
  "desperdício": {
    "feminine": "/audio/pt-pt/feminine-118e30db41403a47.mp3",
    "masculine": "/audio/pt-pt/masculine-088ccd7da46dcb51.mp3"
  },
  "já": {
    "feminine": "/audio/pt-pt/feminine-eb37b19e2abcfecb.mp3",
    "masculine": "/audio/pt-pt/masculine-8f1fb645806ea8d7.mp3"
  },
  "desde": {
    "feminine": "/audio/pt-pt/feminine-fa827404fe0725a2.mp3",
    "masculine": "/audio/pt-pt/masculine-0b7592495ea304a7.mp3"
  },
  "reunir": {
    "feminine": "/audio/pt-pt/feminine-47b9cbb135a5b192.mp3",
    "masculine": "/audio/pt-pt/masculine-e9a76161e29c9b15.mp3"
  },
  "comigo": {
    "feminine": "/audio/pt-pt/feminine-96599b39af987dd5.mp3",
    "masculine": "/audio/pt-pt/masculine-c5bd077fc707f865.mp3"
  },
  "soubesse": {
    "feminine": "/audio/pt-pt/feminine-929fd9ef9d1b9ef9.mp3",
    "masculine": "/audio/pt-pt/masculine-f1e27d15a05e7a05.mp3"
  },
  "disponibilidade": {
    "feminine": "/audio/pt-pt/feminine-12930484e0d48141.mp3",
    "masculine": "/audio/pt-pt/masculine-561825cc8d4c6a15.mp3"
  },
  "ia": {
    "feminine": "/audio/pt-pt/feminine-90deebe1a62aeef8.mp3",
    "masculine": "/audio/pt-pt/masculine-a81c643dfb721205.mp3"
  },
  "tanto": {
    "feminine": "/audio/pt-pt/feminine-cd28407e39b2e069.mp3",
    "masculine": "/audio/pt-pt/masculine-aac27093ab36ff8c.mp3"
  },
  "demorar": {
    "feminine": "/audio/pt-pt/feminine-4c8e1e4d3481db4a.mp3",
    "masculine": "/audio/pt-pt/masculine-f0935b5b2b7aac83.mp3"
  },
  "teria": {
    "feminine": "/audio/pt-pt/feminine-56099ef48adbe28a.mp3",
    "masculine": "/audio/pt-pt/masculine-e350ad187a559365.mp3"
  },
  "saído": {
    "feminine": "/audio/pt-pt/feminine-5d1bc7a2929affb8.mp3",
    "masculine": "/audio/pt-pt/masculine-ab7c23a95db9fa8d.mp3"
  },
  "faças": {
    "feminine": "/audio/pt-pt/feminine-61f72de97be20fce.mp3",
    "masculine": "/audio/pt-pt/masculine-0f41ce0ceeeba16f.mp3"
  },
  "Desde": {
    "feminine": "/audio/pt-pt/feminine-29ac4728bf837716.mp3",
    "masculine": "/audio/pt-pt/masculine-c6d47c6e360a11ba.mp3"
  },
  "não": {
    "feminine": "/audio/pt-pt/feminine-153a5f97f3945c13.mp3",
    "masculine": "/audio/pt-pt/masculine-4b8af3189e6cd6a7.mp3"
  },
  "haverá": {
    "feminine": "/audio/pt-pt/feminine-a2ab32165717f1db.mp3",
    "masculine": "/audio/pt-pt/masculine-0fa294a667af27f0.mp3"
  },
  "qualquer": {
    "feminine": "/audio/pt-pt/feminine-5ba5c1af1527f862.mp3",
    "masculine": "/audio/pt-pt/masculine-527865e5c104f86c.mp3"
  },
  "tente": {
    "feminine": "/audio/pt-pt/feminine-bda61adba07baa0f.mp3",
    "masculine": "/audio/pt-pt/masculine-3bc56bc1f11f8557.mp3"
  },
  "situação": {
    "feminine": "/audio/pt-pt/feminine-d06689df3339fa36.mp3",
    "masculine": "/audio/pt-pt/masculine-d06faa3b648ba3c3.mp3"
  },
  "habituar": {
    "feminine": "/audio/pt-pt/feminine-abfd91059f9d962a.mp3",
    "masculine": "/audio/pt-pt/masculine-752b4ccc6f5462fb.mp3"
  },
  "Oxalá": {
    "feminine": "/audio/pt-pt/feminine-3b35ca96f6286cd6.mp3",
    "masculine": "/audio/pt-pt/masculine-1fde7106dfa4a955.mp3"
  },
  "sotaque": {
    "feminine": "/audio/pt-pt/feminine-87395f4d051c97ad.mp3",
    "masculine": "/audio/pt-pt/masculine-07dd0d980925da8b.mp3"
  },
  "rapidamente": {
    "feminine": "/audio/pt-pt/feminine-31d88c8a66a25eee.mp3",
    "masculine": "/audio/pt-pt/masculine-3e8e82cea3559093.mp3"
  },
  "resolva": {
    "feminine": "/audio/pt-pt/feminine-1904616e3a7a2c41.mp3",
    "masculine": "/audio/pt-pt/masculine-a007a1c7abc6ae2a.mp3"
  },
  "possível": {
    "feminine": "/audio/pt-pt/feminine-3b2790b9afd97fe3.mp3",
    "masculine": "/audio/pt-pt/masculine-6fc9264f7f2c61ba.mp3"
  },
  "menos": {
    "feminine": "/audio/pt-pt/feminine-2608ace5cad4b105.mp3",
    "masculine": "/audio/pt-pt/masculine-b2785147365a334a.mp3"
  },
  "objeções": {
    "feminine": "/audio/pt-pt/feminine-39a7c2e0ea66c373.mp3",
    "masculine": "/audio/pt-pt/masculine-894ba20830b1b796.mp3"
  },
  "daremos": {
    "feminine": "/audio/pt-pt/feminine-7d850e8d251656f1.mp3",
    "masculine": "/audio/pt-pt/masculine-7eb204be10a1c1c3.mp3"
  },
  "surjam": {
    "feminine": "/audio/pt-pt/feminine-888a7de580b8dc17.mp3",
    "masculine": "/audio/pt-pt/masculine-978592ef333da614.mp3"
  },
  "projeto": {
    "feminine": "/audio/pt-pt/feminine-d4905572dfd53056.mp3",
    "masculine": "/audio/pt-pt/masculine-294abcbd6fd46df7.mp3"
  },
  "concluído": {
    "feminine": "/audio/pt-pt/feminine-b6a7d6d5b0033960.mp3",
    "masculine": "/audio/pt-pt/masculine-49755468a89e687d.mp3"
  },
  "Temos": {
    "feminine": "/audio/pt-pt/feminine-c5e28384769e83b2.mp3",
    "masculine": "/audio/pt-pt/masculine-0035e6bec1d943c2.mp3"
  },
  "encarar": {
    "feminine": "/audio/pt-pt/feminine-9bd230b93468800f.mp3",
    "masculine": "/audio/pt-pt/masculine-6a68fd919fbcc788.mp3"
  },
  "factos": {
    "feminine": "/audio/pt-pt/feminine-58b2d42e3d9ff613.mp3",
    "masculine": "/audio/pt-pt/masculine-5082c3bee1c6344b.mp3"
  },
  "as": {
    "feminine": "/audio/pt-pt/feminine-6b6f098d6797207b.mp3",
    "masculine": "/audio/pt-pt/masculine-2543fece7d6b36be.mp3"
  },
  "correram": {
    "feminine": "/audio/pt-pt/feminine-ee4d02295589482f.mp3",
    "masculine": "/audio/pt-pt/masculine-66be2d12a0749a79.mp3"
  },
  "como": {
    "feminine": "/audio/pt-pt/feminine-9331be3cf0e9e9c8.mp3",
    "masculine": "/audio/pt-pt/masculine-5d2370e795638062.mp3"
  },
  "planeado": {
    "feminine": "/audio/pt-pt/feminine-e890731696a358ad.mp3",
    "masculine": "/audio/pt-pt/masculine-87475fe871abcdf3.mp3"
  },
  "coisas": {
    "feminine": "/audio/pt-pt/feminine-e3c1a1a4f503e8c6.mp3",
    "masculine": "/audio/pt-pt/masculine-bc4ede32f41e96d6.mp3"
  },
  "prevenir": {
    "feminine": "/audio/pt-pt/feminine-3979c1d0111ba2da.mp3",
    "masculine": "/audio/pt-pt/masculine-1ac9b953c80a5e4f.mp3"
  },
  "Vale": {
    "feminine": "/audio/pt-pt/feminine-6104c98f1f1b03d4.mp3",
    "masculine": "/audio/pt-pt/masculine-a79a8bfd4c4da435.mp3"
  },
  "ter": {
    "feminine": "/audio/pt-pt/feminine-a07211c332e72ec6.mp3",
    "masculine": "/audio/pt-pt/masculine-13658968b0fed55b.mp3"
  },
  "remediar": {
    "feminine": "/audio/pt-pt/feminine-7d02164679fe323d.mp3",
    "masculine": "/audio/pt-pt/masculine-1f2e837d679ebcc0.mp3"
  },
  "convém": {
    "feminine": "/audio/pt-pt/feminine-eda57de2a89d6179.mp3",
    "masculine": "/audio/pt-pt/masculine-adcf70c283d7e246.mp3"
  },
  "cuidado": {
    "feminine": "/audio/pt-pt/feminine-1dccc0de9eb2e67e.mp3",
    "masculine": "/audio/pt-pt/masculine-52f8268a2bbcae0e.mp3"
  },
  "Isso": {
    "feminine": "/audio/pt-pt/feminine-bd86d4ec4b96bc70.mp3",
    "masculine": "/audio/pt-pt/masculine-6b7a841324c71003.mp3"
  },
  "menor": {
    "feminine": "/audio/pt-pt/feminine-7333f13b71e63f68.mp3",
    "masculine": "/audio/pt-pt/masculine-e3bb38857a5e932c.mp3"
  },
  "sentido": {
    "feminine": "/audio/pt-pt/feminine-7d6407b38a2b6478.mp3",
    "masculine": "/audio/pt-pt/masculine-de355f5170dbf452.mp3"
  },
  "estás": {
    "feminine": "/audio/pt-pt/feminine-2fe2399b7e30a408.mp3",
    "masculine": "/audio/pt-pt/masculine-d9a3b10d14fd050e.mp3"
  },
  "contrário": {
    "feminine": "/audio/pt-pt/feminine-ec9f1f50047bfafb.mp3",
    "masculine": "/audio/pt-pt/masculine-08c4b5abff531c50.mp3"
  },
  "toca": {
    "feminine": "/audio/pt-pt/feminine-f5606f92a3b44cba.mp3",
    "masculine": "/audio/pt-pt/masculine-35ee92313209f08b.mp3"
  },
  "assunto": {
    "feminine": "/audio/pt-pt/feminine-0e8eebaacfa28b84.mp3",
    "masculine": "/audio/pt-pt/masculine-664e01ff7f70579b.mp3"
  },
  "manter-me": {
    "feminine": "/audio/pt-pt/feminine-269d619dcf180ca1.mp3",
    "masculine": "/audio/pt-pt/masculine-ded72a763e408b00.mp3"
  },
  "prefiro": {
    "feminine": "/audio/pt-pt/feminine-7d490be1f925245d.mp3",
    "masculine": "/audio/pt-pt/masculine-6f144c2759f1b461.mp3"
  },
  "neutro": {
    "feminine": "/audio/pt-pt/feminine-1a13ca8a4066a0b6.mp3",
    "masculine": "/audio/pt-pt/masculine-1bf94bd6cd823976.mp3"
  },
  "vale": {
    "feminine": "/audio/pt-pt/feminine-320284a6085274ac.mp3",
    "masculine": "/audio/pt-pt/masculine-cc99b0bdbeb68364.mp3"
  },
  "chorar": {
    "feminine": "/audio/pt-pt/feminine-ae87bad167936e58.mp3",
    "masculine": "/audio/pt-pt/masculine-2d6b8223228d8e42.mp3"
  },
  "pena": {
    "feminine": "/audio/pt-pt/feminine-cad0e16112e64f73.mp3",
    "masculine": "/audio/pt-pt/masculine-2337a306055522cd.mp3"
  },
  "sobre": {
    "feminine": "/audio/pt-pt/feminine-bbbcb034533c474c.mp3",
    "masculine": "/audio/pt-pt/masculine-2112730f13db9cbe.mp3"
  },
  "derramado": {
    "feminine": "/audio/pt-pt/feminine-5fd18d85757166a1.mp3",
    "masculine": "/audio/pt-pt/masculine-3b114e78051ebe37.mp3"
  },
  "Estás": {
    "feminine": "/audio/pt-pt/feminine-7c036b14b34e3484.mp3",
    "masculine": "/audio/pt-pt/masculine-9ccd2e8c0fafe8f4.mp3"
  },
  "temos": {
    "feminine": "/audio/pt-pt/feminine-a77109508f41b318.mp3",
    "masculine": "/audio/pt-pt/masculine-08642b4392670ada.mp3"
  },
  "dar": {
    "feminine": "/audio/pt-pt/feminine-011e2ef424163daf.mp3",
    "masculine": "/audio/pt-pt/masculine-541524640d7e44f5.mp3"
  },
  "avançar": {
    "feminine": "/audio/pt-pt/feminine-9b5c0344387ae19f.mp3",
    "masculine": "/audio/pt-pt/masculine-7ebe1633fa731278.mp3"
  },
  "graxa": {
    "feminine": "/audio/pt-pt/feminine-93f60f746d304969.mp3",
    "masculine": "/audio/pt-pt/masculine-f4b046cca5a0367c.mp3"
  },
  "chefe": {
    "feminine": "/audio/pt-pt/feminine-d8dc6f8dda9b6e3f.mp3",
    "masculine": "/audio/pt-pt/masculine-d51764455f8351f5.mp3"
  },
  "promoção": {
    "feminine": "/audio/pt-pt/feminine-97431838046e3c96.mp3",
    "masculine": "/audio/pt-pt/masculine-da4df4a4941eafdf.mp3"
  },
  "consegues": {
    "feminine": "/audio/pt-pt/feminine-77b39f3ff75ad4a6.mp3",
    "masculine": "/audio/pt-pt/masculine-7b0c26bddeaf8a4c.mp3"
  },
  "Ficámos": {
    "feminine": "/audio/pt-pt/feminine-0364be4bc5828180.mp3",
    "masculine": "/audio/pt-pt/masculine-0ad78727c9d30a59.mp3"
  },
  "porque": {
    "feminine": "/audio/pt-pt/feminine-d5d9c33b4d178f07.mp3",
    "masculine": "/audio/pt-pt/masculine-2d7c43678afca4a8.mp3"
  },
  "fornecedor": {
    "feminine": "/audio/pt-pt/feminine-3e668260b8481363.mp3",
    "masculine": "/audio/pt-pt/masculine-b398c30c91861c97.mp3"
  },
  "navios": {
    "feminine": "/audio/pt-pt/feminine-ce7e005114fca8fa.mp3",
    "masculine": "/audio/pt-pt/masculine-dfcb2b48593ce83b.mp3"
  },
  "prazo": {
    "feminine": "/audio/pt-pt/feminine-c2e34cb4b6c36c4f.mp3",
    "masculine": "/audio/pt-pt/masculine-7392999ad9bcfc4c.mp3"
  },
  "falhou": {
    "feminine": "/audio/pt-pt/feminine-67232abd0ec53c20.mp3",
    "masculine": "/audio/pt-pt/masculine-6d47a2ea2e334adb.mp3"
  },
  "fiques": {
    "feminine": "/audio/pt-pt/feminine-56b8c3aca6014006.mp3",
    "masculine": "/audio/pt-pt/masculine-9518c88f8815cb0c.mp3"
  },
  "engolir": {
    "feminine": "/audio/pt-pt/feminine-3bc6a22168819ee7.mp3",
    "masculine": "/audio/pt-pt/masculine-40f7707ede6f1247.mp3"
  },
  "claramente": {
    "feminine": "/audio/pt-pt/feminine-55a12e8cee0b39a7.mp3",
    "masculine": "/audio/pt-pt/masculine-58706fc485ee1d28.mp3"
  },
  "sapos": {
    "feminine": "/audio/pt-pt/feminine-88079c7e99e59cb4.mp3",
    "masculine": "/audio/pt-pt/masculine-84a19c9379a806e2.mp3"
  },
  "pensas": {
    "feminine": "/audio/pt-pt/feminine-f8001528f79e73d7.mp3",
    "masculine": "/audio/pt-pt/masculine-f40439a5e92ebdc3.mp3"
  },
  "Aquela": {
    "feminine": "/audio/pt-pt/feminine-7feeedd99e04b71b.mp3",
    "masculine": "/audio/pt-pt/masculine-02c9b3880138f79f.mp3"
  },
  "conversa": {
    "feminine": "/audio/pt-pt/feminine-875c16914611c913.mp3",
    "masculine": "/audio/pt-pt/masculine-acc73efe9c85077e.mp3"
  },
  "foi": {
    "feminine": "/audio/pt-pt/feminine-d3aead2be044394a.mp3",
    "masculine": "/audio/pt-pt/masculine-60c9b907da7a2891.mp3"
  },
  "só": {
    "feminine": "/audio/pt-pt/feminine-6c3ba81570ed769a.mp3",
    "masculine": "/audio/pt-pt/masculine-ad88c945cf95d351.mp3"
  },
  "mudar": {
    "feminine": "/audio/pt-pt/feminine-a5ab7ed659eb76c4.mp3",
    "masculine": "/audio/pt-pt/masculine-0841e9e54375e4b5.mp3"
  },
  "Calma": {
    "feminine": "/audio/pt-pt/feminine-b032ceae9300317e.mp3",
    "masculine": "/audio/pt-pt/masculine-209950e3635c3b4d.mp3"
  },
  "ponhas": {
    "feminine": "/audio/pt-pt/feminine-7468ab9b91c7d22c.mp3",
    "masculine": "/audio/pt-pt/masculine-b2df2166603f8013.mp3"
  },
  "realmente": {
    "feminine": "/audio/pt-pt/feminine-6198b5b1a6845db5.mp3",
    "masculine": "/audio/pt-pt/masculine-a7db870a650fcbe0.mp3"
  },
  "carroça": {
    "feminine": "/audio/pt-pt/feminine-bf42129b221e18bc.mp3",
    "masculine": "/audio/pt-pt/masculine-872fa78cc8b823f6.mp3"
  },
  "dos": {
    "feminine": "/audio/pt-pt/feminine-3cf43626ca48a54a.mp3",
    "masculine": "/audio/pt-pt/masculine-6f00a43ab4d503f2.mp3"
  },
  "bois": {
    "feminine": "/audio/pt-pt/feminine-942b5b561b4ec4a3.mp3",
    "masculine": "/audio/pt-pt/masculine-64a9137548831055.mp3"
  },
  "Continue a aprender português": {
    "feminine": "/audio/pt-pt/feminine-1c6e6c9fd183ea9c.mp3",
    "masculine": "/audio/pt-pt/masculine-2ffbe3736a871b08.mp3"
  },
  "O meu progresso": {
    "feminine": "/audio/pt-pt/feminine-6c8d3e7164cb1e18.mp3",
    "masculine": "/audio/pt-pt/masculine-ba65e474af4552bd.mp3"
  }
};
